Repository comento/comento-ui, pull requests merged in 2020-11, with the labels that each got.

#67 [change] input placeholder 스타일 수정
  src/DataEntry/Input.vue
Labels: enhancement

#68 [change] avatar text v-html로 변경 및 textColor 추가
  src/Components/DataDisplay/Avatar.vue
Labels: enhancement

#69 [add] postcss autoprefixer (크로스브라우징 css 코드 자동 삽입)
  .storybook/webpack.config.js
  package.json
  src/DataEntry/Input.vue
  yarn.lock
Labels: enhancement

#70 [add] githubAction deploy versioned chromatic
  .github/workflows/build-test.yml
  .github/workflows/chromatic.yml
Labels: enhancement

#71 [add] Jest & Jest scripts & Jest example test code
  __test__/Button.test.js
  jest.config.js
  package.json
  yarn.lock
Labels: enhancement

#74 [fix] icon loading 오류 수정
  src/Elements/Core/Icon/Icon.vue
Labels: bug

#75 Feature/add narrow button
  src/Components/Button/Button.vue
  src/Components/Button/NarrowButton.vue
  src/Components/Button/index.js
  src/Elements/Core/Icon/Icon.vue
  stories/Button/Button.stories.js
  stories/Button/Button.stories.mdx
  stories/Button/NarrowButton.stories.mdx
Labels: bug, documentation, enhancement

#77 Release
  src/Components/Layout/Grid.vue
  src/Components/Layout/StyleCol.vue
  src/DataEntry/Input.vue
  stories/Layout/Layout.stories.js
Labels: enhancement

#76 Modal 컴포넌트 구조 대변경
  assets/style/base/utils.scss
  src/Components/Message/Modal.vue
  src/Components/Message/Modal/BasicModal.vue
  src/Components/Message/Modal/FullscreenModal.vue
  src/Components/Message/Modal/Modal.vue
  src/Components/Message/Modal/PermissionModal.vue
  src/Components/Message/Modal/WithFormModal.vue
  src/Components/Message/index.js
  src/DataEntry/Input.vue
  stories/Modal/BasicModal.stories.mdx
  stories/Modal/FullscreenModal.stories.mdx
  stories/Modal/Modal.stories.js
  stories/Modal/PermissionModal.stories.mdx
  stories/Modal/WithFormModal.stories.mdx
Labels: documentation, enhancement

#72 [change] avatar 구조 변경, storybook 추가
  assets/style/base/utils.scss
  src/Components/DataDisplay/Avatar.vue
  stories/DataDisplay/DataDisplay.stories.js
Labels: bug, documentation

#80 [add] 스토리북에 spoqa 폰트 적용
  .storybook/preview-head.html
Labels: enhancement

#81 Checkbox component&docs, Input id
  src/DataEntry/Checkbox.vue
  src/DataEntry/Input.vue
  src/DataEntry/index.js
  stories/DataEntry/Checkbox.stories.mdx
Labels: bug, documentation, enhancement

#79 LinkButton
  src/Components/Button/LinkButton.vue
  src/Components/Button/index.js
  stories/Button/LinkButton.stories.mdx
Labels: documentation, enhancement

#82 Box 개선
  .storybook/preview.js
  mixins/colorMixin.js
  mixins/index.js
  mixins/paddingMixin.js
  mixins/windowMixin.js
  src/Components/DataDisplay/Box.vue
  src/Elements/Core/Colors/index.js
  src/main.js
  stories/Box/Box.stories.mdx
Labels: documentation, enhancement

#85 [add] modal import
  src/Components/Message/Modal/index.js
  src/Components/Message/index.js
Labels: bug

#89 [fix] modal export
  src/Components/Message/index.js
Labels: bug

#91 Toast 변경 & Docs 추가, security Icon 추가
  assets/images/icon/icon-security-large-fill.svg
  src/Components/Message/Toast.vue
  src/Elements/Core/Icon/Icon.vue
  stories/Message/Modal/BasicModal.stories.mdx
  stories/Message/Modal/FullscreenModal.stories.mdx
  stories/Message/Modal/PermissionModal.stories.mdx
  stories/Message/Modal/WithFormModal.stories.mdx
  stories/Message/Toast/Toast.stories.mdx
  stories/Toast/Toast.stories.js
Labels: enhancement

#93 [fix] Button loading style
  src/Components/Button/Button.vue
Labels: bug

#96 [fix] ie에서 storybook 작동안하는 이슈 해결
  .storybook/webpack.config.js
Labels: bug

#95 [fix] toast 수정
  src/Components/Message/Toast.vue
Labels: enhancement

#97 [fix] Checkbox style 변경
  src/DataEntry/Checkbox.vue
Labels: bug, enhancement

#99 [change] LinkButton color
  src/Components/Button/LinkButton.vue
Labels: enhancement

#104 Input, WithFormModal 변경
  src/Components/Message/Modal/WithFormModal.vue
  src/DataEntry/Input.vue
Labels: bug, enhancement

#101 [change] LinkButton docs
  stories/Button/LinkButton.stories.mdx
Labels: documentation

#102 [fix] Toast style
  src/Components/Message/Toast.vue
Labels: bug

#103 Button 컴포넌트 변경, Docs With Icon 추가
  src/Components/Button/Button.vue
  stories/Button/Button.stories.mdx
Labels: bug, documentation, enhancement

#105 [add] Avatar docs
  src/Components/DataDisplay/Avatar.vue
  stories/DataDisplay/Avatar.stories.mdx
  stories/DataDisplay/DataDisplay.stories.js
Labels: documentation

#108 [remove] NarrowButton min-width 제거
  src/Components/Button/NarrowButton.vue
Labels: enhancement

#110 [change] Modal pc maxHeight
  src/Components/Message/Modal/BasicModal.vue
  src/Components/Message/Modal/Modal.vue
  src/Components/Message/Modal/WithFormModal.vue
Labels: enhancement

#112 Fix: ie issue
  package.json
  src/Elements/Core/Icon/Icon.vue
Labels: bug

#113 Modal 개선, Input align 오류 수정
  src/Components/Message/Modal/BasicModal.vue
  src/Components/Message/Modal/FullscreenModal.vue
  src/Components/Message/Modal/Modal.vue
  src/Components/Message/Modal/PermissionModal.vue
  src/Components/Message/Modal/WithFormModal.vue
  src/DataEntry/Input.vue
  stories/Message/Modal/BasicModal.stories.mdx
  stories/Message/Modal/WithFormModal.stories.mdx
Labels: bug, documentation, enhancement

#114 [change] 폴더 구조 변경, drawer export
  src/Components/DataDisplay/Drawer/BottomDrawer.vue
  src/Components/DataDisplay/Drawer/BottomDrawerExample.vue
  src/Components/DataDisplay/Drawer/Drawer.vue
  src/Components/DataDisplay/Drawer/SideDrawer.vue
  src/Components/DataDisplay/Drawer/SideDrawerExample.vue
  src/Components/DataDisplay/Drawer/index.js
  src/Components/DataDisplay/index.js
  src/Components/DataEntry/Checkbox.vue
  src/Components/DataEntry/Dropdown.vue
  src/Components/DataEntry/Input.vue
  src/Components/DataEntry/SearchInput.vue
  src/Components/DataEntry/TextArea.vue
  src/Components/DataEntry/index.js
  src/main.js
  stories/DataDisplay/BottomDrawer.stories.js
  stories/DataDisplay/Drawer.stories.js
  stories/DataEntry/Checkbox.stories.mdx
  stories/DataEntry/Dropdown.stories.mdx
  stories/Message/Modal/WithFormModal.stories.mdx
Labels: enhancement

#116 BottomDrawer 변경
  src/Components/DataDisplay/Drawer/BottomDrawer.vue
  src/Components/DataDisplay/Drawer/BottomDrawerExample.vue
  src/Components/DataDisplay/Drawer/Drawer.vue
  src/Components/index.js
  stories/DataDisplay/BottomDrawer.stories.js
  stories/DataDisplay/Drawer.stories.js
  stories/DataDisplay/SideDrawer.stories.js
Labels: enhancement

#119 Input error 속성과 style 추가
  src/Components/DataEntry/Input.vue
Labels: enhancement

#118 [fix] Avatar background-size 100% 100%로 변경
  src/Components/DataDisplay/Avatar.vue
Labels: bug

#121 [fix] Button disabled 오류 수정
  src/Components/Button/Button.vue
  stories/Button/Button.stories.mdx
Labels: bug, documentation

#123 Feature/change components styles
  src/Components/DataEntry/Dropdown.vue
  src/Components/DataEntry/Input.vue
  src/Components/Message/Callout.vue
  stories/DataEntry/Dropdown.stories.mdx
Labels: enhancement

#124 [fix] Toast width 오류 수정
  src/Components/Message/Toast.vue
Labels: bug

#125 [change] BasicModal, WithFormModal 구조, style 변경
  src/Components/Message/Modal/BasicModal.vue
  src/Components/Message/Modal/PermissionModal.vue
  src/Components/Message/Modal/WithFormModal.vue
Labels: enhancement

#128 [fix] Dropdown maxHeight 속성 추가, 클래스명 변경
  src/Components/DataEntry/Dropdown.vue
  stories/DataEntry/Dropdown.stories.mdx
Labels: enhancement

#129 [add] WithFormModal, BasicModal mobile max-height
  src/Components/Message/Modal/BasicModal.vue
  src/Components/Message/Modal/WithFormModal.vue
Labels: enhancement

#132 컴포넌트 스타일 수정
  src/Components/DataEntry/Checkbox.vue
  src/Components/Message/Modal/Modal.vue
  src/Components/Message/Modal/PermissionModal.vue
Labels: bug

#131 [add] ListItem outline 제거
  src/Components/DataDisplay/ListItem.vue
Labels: enhancement

#135 [change] 패키지 & 스토리북 css webpack 설정 변경
  .storybook/preview.js
  assets/style/base/global.scss
  assets/style/base/main.scss
  src/main.js
Labels: enhancement

#134 코멘토 core style 적용
  assets/style/base/functions.scss
  assets/style/base/global.scss
  assets/style/base/grid.scss
  assets/style/base/init.scss
  assets/style/base/mixins.scss
  assets/style/base/reset.scss
  assets/style/base/variables.scss
  src/Components/Button/Button.vue
  src/Components/Button/LinkButton.vue
  src/Components/Button/NarrowButton.vue
  src/Components/DataDisplay/Box.vue
  src/Components/DataDisplay/Card.vue
  src/Components/DataDisplay/Drawer/BottomDrawer.vue
  src/Components/DataDisplay/Drawer/Drawer.vue
  src/Components/DataDisplay/Drawer/SideDrawer.vue
  src/Components/DataDisplay/ListItem.vue
  src/Components/DataDisplay/Tab.vue
  src/Components/DataEntry/Checkbox.vue
  src/Components/DataEntry/SearchInput.vue
  src/Components/Message/Toast.vue
  src/Elements/Core/Colors/Index.vue
  src/Elements/Core/Icon/Icon.vue
  src/Elements/Core/Logo/Logo.vue
  src/Elements/Core/Typography/Typography.vue
  src/Elements/Utility/Divider.vue
  stories/DataEntry/Dropdown.stories.mdx
Labels: enhancement

#137 모달이 켜졌으면 overlay 영역 스크롤 막기
  assets/style/base/utils.scss
  src/Components/Message/Modal/Modal.vue
Labels: enhancement

#136 InputGroup 추가, WithFormModal docs 변경
  src/Components/DataEntry/Input.vue
  src/Components/DataEntry/InputGroup.vue
  src/Components/DataEntry/index.js
  src/Components/Message/Modal/WithFormModal.vue
  stories/Message/Modal/WithFormModal.stories.mdx
Labels: documentation, enhancement
