Repository comento/comento-ui, pull requests merged in 2020-12, with the labels that each got.

#139 not-scroll html에도 추가
  assets/style/base/init.scss
  src/Components/Message/Modal/Modal.vue
Labels: bug

#140 Drawer 개선
  src/Components/DataDisplay/Drawer/BottomDrawer.vue
  src/Components/DataDisplay/Drawer/BottomDrawerExample.vue
  src/Components/DataDisplay/Drawer/Drawer.vue
  src/Components/DataDisplay/Drawer/SideDrawer.vue
  stories/Message/Modal/BasicModal.stories.mdx
Labels: enhancement

#142 overlay영역 스크롤 막는 코드 개선
  mixins/scrollMixin.js
  src/Components/DataDisplay/Drawer/BottomDrawer.vue
  src/Components/DataDisplay/Drawer/Drawer.vue
  src/Components/DataDisplay/Drawer/SideDrawer.vue
  src/Components/Message/Modal/Modal.vue
Labels: enhancement

#144 [change] main grid container width 1170px -> 1140px
  src/Components/Layout/Grid.vue
Labels: enhancement

#145 Feature/add shadow comments
  assets/style/base/mixins.scss
  stories/BoxWithShadow.vue
  stories/Shadow.stories.js
Labels: documentation

#146 Logo 개선, docs 추가
  src/Elements/Core/Logo/Logo.vue
  stories/Logo/Logo.stories.mdx
Labels: documentation, enhancement

#147 InputGroup 개선, Docs 추가
  src/Components/DataEntry/InputGroup.vue
  stories/DataEntry/InputGroup.stories.js
Labels: documentation, enhancement

#148 Feature/add icons
  assets/images/icon/icon-arrow-large-line.svg
  assets/images/icon/icon-arrow-xlarge-line.svg
  assets/images/icon/icon-check-small-line.svg
  assets/images/icon/icon-checkCircle-medium-fill.svg
  assets/images/icon/icon-checkRound-medium-line.svg
  assets/images/icon/icon-close-small-line.svg
  assets/images/icon/icon-coupon-medium-line.svg
  assets/images/icon/icon-download-medium-line-light.svg
  assets/images/icon/icon-edu-large-line.svg
  assets/images/icon/icon-edu-medium-line.svg
  assets/images/icon/icon-essay-medium-line.svg
  assets/images/icon/icon-file-medium-line-light.svg
  assets/images/icon/icon-interview-medium-line.svg
  assets/images/icon/icon-like-medium-line.svg
  assets/images/icon/icon-like-xlarge-line.svg
  assets/images/icon/icon-location-medium-fill.svg
  assets/images/icon/icon-mentoring-medium-line.svg
  assets/images/icon/icon-profile-2xlarge-fill.svg
  assets/images/icon/icon-profile-xlarge-fill.svg
  assets/images/icon/icon-question-large-line.svg
  assets/images/icon/icon-resume-large-line.svg
  assets/images/icon/icon-send-large-fill.svg
  assets/images/icon/icon-sercurity-large-fill.svg
  assets/images/icon/icon-trash-medium-line-light.svg
  assets/images/icon/icon-vod-medium-line.svg
  src/Elements/Core/Colors/index.js
  src/Elements/Core/Icon/Icon.vue
  stories/Icon/Icon.stories.js
  stories/Icon/Icon.stories.mdx
Labels: enhancement

#151 ListItem cursor 추가, docs 개선
  assets/style/base/utils.scss
  src/Components/DataDisplay/ListItem.vue
  stories/DataDisplay/ListItem.stories.mdx
Labels: enhancement

#152 List 개선
  src/Components/DataDisplay/List.vue
  stories/DataDisplay/List.stories.mdx
Labels: documentation, enhancement

#156 [change] 스타일 초기화 파일명 변경(reset -> normalize)
  assets/style/base/global.scss
  assets/style/base/normalize.scss
Labels: enhancement

#154 NarrowButton 개선
  src/Components/Button/NarrowButton.vue
  stories/Button/NarrowButton.stories.mdx
Labels: documentation, enhancement

#153 [add] Icon rotation
  src/Elements/Core/Icon/Icon.vue
  stories/Icon/Icon.stories.mdx
Labels: enhancement

#149 Feature/add tooltip docs
  src/Components/Message/Tooltip.vue
  stories/Components/Message/Tooltip.stories.mdx
Labels: documentation

#150 Avatar 컴포넌트, docs 개선
  src/Components/DataDisplay/Avatar.vue
  stories/DataDisplay/Avatar.stories.mdx
Labels: enhancement

#158 [add] styleColGroup 추가 및 grid, row,styleCol 파일 확인
  src/Components/Layout/StyleCol.vue
  src/Components/Layout/StyleColGroup.vue
  stories/Layout/Layout.stories.js
Labels: documentation

#159 [add] contents
  src/Components/DataDisplay/Contents.vue
  stories/DataDisplay/Contetns.stories.mdx
Labels: documentation

#155 Feature/add typography docs
  src/Elements/Core/Typography/Typography.vue
  stories/Typography/Typography.stories.mdx
Labels: documentation, enhancement

#162 ButtonGroup Component, docs 추가
  src/Components/Button/ButtonGroup.vue
  src/Components/Button/index.js
  stories/Button/ButtonGroup.stories.mdx
Labels: documentation, enhancement

#163 NarrowButton Component, Docs 개선
  assets/style/base/utils.scss
  src/Components/Button/NarrowButton.vue
  stories/Button/NarrowButton.stories.mdx
Labels: documentation, enhancement

#166 LinkButton Component, Docs 개선
  src/Components/Button/LinkButton.vue
  stories/Button/LinkButton.stories.mdx
Labels: documentation, enhancement

#160 [add] chip, chipGroup 추가
  src/Components/DataDisplay/Chip.vue
  src/Components/DataDisplay/ChipGroup.vue
  stories/DataDisplay/Chip.stories.mdx
  stories/DataDisplay/ChipGroup.stories.mdx
Labels: documentation

#167 [change] IconOverflow -> IconThreedot
  assets/images/icon/icon-threeDot-medium-fill.svg
  assets/images/icon/icon-threeDot-small-fill.svg
  src/Elements/Core/Icon/Icon.vue
  stories/Icon/Icon.stories.mdx
Labels: enhancement

#168 Feature/change box
  src/Components/DataDisplay/Box.vue
  stories/Box/Box.stories.mdx
Labels: documentation

#171 [fix] contents -> content
  src/Components/DataDisplay/Content.vue
  stories/DataDisplay/Content.stories.mdx
Labels: documentation, enhancement

#173 [remove] contents 관련파일 삭제
  src/Components/DataDisplay/Contents.vue
  src/Components/DataDisplay/index.js
  stories/DataDisplay/Chip.stories.mdx
  stories/DataDisplay/ChipGroup.stories.mdx
  stories/DataDisplay/Content.stories.mdx
  stories/DataDisplay/Contetns.stories.mdx
Labels: documentation

#172 [add] 빠진 컴포넌트 등록 & 순서변경 (알파벳순)
  src/Components/DataDisplay/index.js
  src/Components/DataEntry/index.js
  src/Components/Layout/index.js
  src/Components/Message/Modal/index.js
  src/Components/Message/index.js
Labels: enhancement

#164 Checkbox 개선
  src/Components/DataEntry/Checkbox.vue
  stories/DataEntry/Checkbox.stories.mdx
Labels: documentation, enhancement

#169 Button 개선
  assets/style/base/utils.scss
  src/Components/Button/Button.vue
  src/Elements/Core/Icon/Icon.vue
  stories/Button/Button.stories.mdx
Labels: documentation, enhancement

#161 Feature/change color
  assets/style/base/color.scss
  assets/style/base/utils.scss
  src/Components/Button/Button.vue
  src/Components/DataDisplay/Card.vue
  src/Components/DataDisplay/index.js
  src/Components/DataEntry/Checkbox.vue
  src/Components/DataEntry/Input.vue
  src/Components/DataEntry/SearchInput.vue
  src/Components/DataEntry/index.js
  src/Components/Layout/index.js
  src/Components/Message/Modal/BasicModal.vue
  src/Components/Message/Modal/PermissionModal.vue
  src/Components/Message/Modal/WithFormModal.vue
  src/Components/Message/Modal/index.js
  src/Components/Message/Popover.vue
  src/Components/Message/Toast.vue
  src/Components/Message/index.js
  src/Elements/Core/Colors/index.js
  src/Elements/Core/Icon/Icon.vue
  stories/Button/Button.stories.mdx
  stories/DataDisplay/Chip.stories.mdx
  stories/DataDisplay/ChipGroup.stories.mdx
  stories/DataEntry/Checkbox.stories.mdx
Labels: enhancement

#176 Feature/change popover
  assets/style/tooltip/popover.scss
  src/Components/Message/Popover.vue
  stories/Components/Message/Popover.stories.mdx
Labels: documentation, enhancement

#177 [change] 스토리북 컴포넌트들 Meta title 계층 Level2에 맞게 변경
  stories/Button/Button.stories.mdx
  stories/Callout/Callout.stories.js
  stories/Callout/Callout.stories.mdx
  stories/Card/Card.stories.js
  stories/Color.stories.js
  stories/DataDisplay/BottomDrawer.stories.js
  stories/DataDisplay/Chip.stories.mdx
  stories/DataDisplay/ChipGroup.stories.mdx
  stories/DataDisplay/SideDrawer.stories.js
  stories/DataEntry/Checkbox.stories.mdx
  stories/DataEntry/Dropdown.stories.mdx
  stories/DataEntry/InputGroup.stories.js
  stories/Logo/Logo.stories.mdx
  stories/Message/Modal/BasicModal.stories.mdx
  stories/Message/Modal/FullscreenModal.stories.mdx
  stories/Message/Modal/PermissionModal.stories.mdx
  stories/Message/Modal/WithFormModal.stories.mdx
  stories/Message/Toast/Toast.stories.mdx
Labels: documentation

#181 스토리북 기본 Story name, Meta title 변경
  stories/Button/Button.stories.mdx
  stories/DataDisplay/ChipGroup.stories.mdx
  stories/Logo/Logo.stories.mdx
  stories/Message/Toast/Toast.stories.mdx
Labels: documentation

#180 [add] test storybook deployer github action
  .github/workflows/test.yml
Labels: enhancement

#193 Feature/add storybook deployer GitHub action
  .github/workflows/storybook-deployer.yml
Labels: enhancement

#194 [add] ListItem 세로 가운데 정렬
  src/Components/DataDisplay/ListItem.vue
Labels: enhancement

#189 컴포넌트 등록 알파벳순 정렬 (#161 일부 원복)
  src/Components/DataDisplay/index.js
  src/Components/DataEntry/index.js
  src/Components/Layout/index.js
  src/Components/Message/Modal/index.js
  src/Components/Message/index.js
Labels: bug

#183 Avatar item에 display flex 추가
  src/Components/DataDisplay/Avatar.vue
Labels: bug

#188 Checkbox 개선 (#164 원복)
  src/Components/DataEntry/Checkbox.vue
  stories/DataEntry/Checkbox.stories.mdx
Labels: bug

#184 LinkButton type validator 개선, style 오류 수정
  src/Components/Button/LinkButton.vue
  stories/Button/LinkButton.stories.mdx
Labels: bug, enhancement

#187 Button 개선 (#169 원복), color gray -> secondary로 변경
  assets/style/base/color.scss
  assets/style/base/utils.scss
  src/Components/Button/Button.vue
  src/Elements/Core/Colors/index.js
  src/Elements/Core/Icon/Icon.vue
  stories/Button/Button.stories.mdx
Labels: bug

#178 Feature/add loader
  src/Components/Other/Loader.vue
  src/Components/Other/index.js
  src/Components/index.js
  stories/Components/Other/Loader.stories.mdx
Labels: documentation, enhancement

#197 [change] rotations props -> rotate
  src/Elements/Core/Icon/Icon.vue
  stories/Icon/Icon.stories.mdx
Labels: enhancement

#186 Logo 개선
  assets/images/logo/logo-comento-horizontal.svg
  src/Elements/Core/Logo/Logo.vue
Labels: bug, enhancement

#185 List spacing 오류 수정
  src/Components/DataDisplay/List.vue
Labels: bug

#196 Feature/change typography
  src/Elements/Core/Typography/Typography.vue
  stories/Typography/Typography.stories.mdx
Labels: documentation, enhancement

#200 [add] overlay
  src/Elements/Utility/Overlay.vue
  src/Elements/Utility/index.js
  stories/Overlay.stories.mdx
Labels: documentation, enhancement

#205 Feature/change card
  src/Components/DataDisplay/Card.vue
  stories/Card/Card.stories.js
  stories/Card/Card.stories.mdx
  utils/custom-validator.js
Labels: documentation, enhancement

#206 Overlay 개선
  src/Elements/Utility/Overlay.vue
  stories/Overlay.stories.mdx
Labels: enhancement

#209 Change custom validator
  src/Components/DataDisplay/Card.vue
  utils/custom-validator.js
Labels: enhancement

#208 BasicModal 개선
  src/Components/Message/Modal/BasicModal.vue
  stories/Message/Modal/BasicModal.stories.mdx
Labels: enhancement

#203 Feature/change gray to secondary
  src/Components/Button/Button.vue
  src/Components/DataDisplay/Chip.vue
  src/Elements/Core/Icon/Icon.vue
  stories/Button/Button.stories.mdx
  stories/Button/ButtonGroup.stories.mdx
  stories/DataDisplay/Chip.stories.mdx
  stories/Icon/Icon.stories.mdx
Labels: documentation, enhancement

#207 Modal 개선
  src/Components/Message/Modal/Modal.vue
Labels: enhancement

#202 Feature/change callout
  src/Components/Message/Callout.vue
  stories/Callout/Callout.stories.js
  stories/Callout/Callout.stories.mdx
Labels: documentation, enhancement

#201 [add] label
  src/Components/DataDisplay/Label.vue
  stories/DataDisplay/Label.stories.mdx
Labels: documentation, enhancement

#211 Feature/fix storybook deployer
  .github/workflows/storybook-deployer.yml
  package.json
Labels: bug

#212 WithFormModal 개선
  src/Components/Message/Modal/WithFormModal.vue
  stories/Message/Modal/WithFormModal.stories.mdx
Labels: enhancement

#217 [fix] Overlay close 코드 개선
  src/Components/Message/Modal/Modal.vue
  src/Elements/Utility/Overlay.vue
Labels: bug

#216 FullscreenModal 개선
  src/Components/Message/Modal/FullscreenModal.vue
  stories/Message/Modal/FullscreenModal.stories.mdx
Labels: enhancement

#204 Feature/change tooltip
  src/Components/Message/Tooltip.vue
  stories/Components/Message/Tooltip.stories.mdx
Labels: documentation, enhancement

#225 [add] divider
  src/Elements/Utility/Divider.vue
  stories/Divider.stories.mdx
Labels: documentation, enhancement

#219 [add] WithFormModal mdx disabled 추가
  stories/Message/Modal/WithFormModal.stories.mdx
Labels: bug

#220 [add] textArea
  src/Components/DataEntry/TextArea.vue
  stories/DataEntry/TextArea.stories.mdx
Labels: documentation, enhancement

#223 [fix] Label props
  src/Components/DataDisplay/Label.vue
Labels: bug

#227 Toast 개선
  src/Components/Message/Toast.vue
  stories/Message/Toast/Toast.stories.mdx
Labels: enhancement

#229 [add] form
  src/Components/DataEntry/Form.vue
  src/Components/DataEntry/index.js
  stories/DataEntry/Form.stories.mdx
Labels: documentation, enhancement

#228 [fix] grid 1170 -> 1140, container 기본 padding 16 ,styleCol 제거
  src/Components/Layout/Grid.vue
  src/Components/Layout/Row.vue
  src/Components/Layout/StyleCol.vue
  src/Components/Layout/StyleColGroup.vue
  src/Components/Layout/index.js
  stories/Layout/Layout.stories.js
Labels: documentation, enhancement

#226 [add] textField
  src/Components/DataEntry/TextField.vue
  src/Components/DataEntry/index.js
  stories/DataEntry/Textfield.stories.mdx
Labels: documentation, enhancement

#234 [add] Typography element props에 'u' 추가
  src/Elements/Core/Typography/Typography.vue
Labels: enhancement

#235 [add] Badge text가 2byte거나 'N'일 때 padding
  src/Components/DataDisplay/Badge.vue
Labels: enhancement

#236 [change] Toast pc position bottom 50px
  src/Components/Message/Toast.vue
Labels: enhancement

#230 Feature/add file input
  src/Components/Button/FileButton.vue
  src/Components/Button/index.js
  src/Components/DataDisplay/FileItem.vue
  src/Components/DataDisplay/FileList.vue
  src/Components/DataDisplay/FileSummary.vue
  src/Components/DataDisplay/index.js
  src/Components/DataEntry/FileInput.vue
  src/Components/DataEntry/index.js
  stories/DataEntry/FileInput.stories.mdx
Labels: documentation, enhancement

#231 Feature/add swiper
  package.json
  src/Components/DataDisplay/Swiper.vue
  src/Components/DataDisplay/index.js
  stories/DataDisplay/Swiper.stories.mdx
  yarn.lock
Labels: documentation, enhancement

#233 Dropdown full 오류 수정, 예시 추가
  src/Components/DataEntry/Dropdown.vue
  stories/DataEntry/Dropdown.stories.mdx
Labels: bug, documentation
