Repository comento/comento-ui, pull requests merged in 2020-10, with the labels that each got.

#15 [add] icon-plus-large-line
  assets/images/icon/icon-plus-large-line.svg
  src/Elements/Core/Icon/Icon.vue
Labels: enhancement

#18 [change] text button color 변경
  src/Components/Button/Button.vue
Labels: enhancement

#17 [add] Box
  src/Components/DataDisplay/Box.vue
  src/Components/DataDisplay/index.js
Labels: enhancement

#16 [change] Tab
  src/Components/DataDisplay/Tab.vue
Labels: enhancement

#12 Feature/add storybook
  src/Components/Button/Button.vue
  src/Elements/Core/Colors/Index.vue
  stories/Button/Button.stories.js
  stories/Button/Button.stories.mdx
  stories/Color.stories.js
Labels: documentation

#23 Feature/add button loading
  assets/style/base/mixins.scss
  assets/style/base/utils.scss
  src/Components/Button/Button.vue
  src/Components/Message/Modal.vue
  src/DataEntry/Input.vue
  src/Elements/Core/Icon/Icon.vue
Labels: enhancement

#24 Feature/add button loading (#23)
  assets/style/base/mixins.scss
  assets/style/base/utils.scss
  src/Components/Button/Button.vue
  src/Components/Message/Modal.vue
  src/DataEntry/Input.vue
  src/Elements/Core/Icon/Icon.vue
Labels: enhancement

#26 [change] 모달 닫을 때 체크메시지 초기화
  src/Components/Message/Modal.vue
Labels: bug

#31 [add] Icon에 리스너 추가
  src/Elements/Core/Icon/Icon.vue
Labels: bug

#35 [fix] update:showSearchDropdown event가 계속 emit되는 이슈 해결
  src/DataEntry/SearchInput.vue
Labels: bug

#33 [add] ghpages에 storybook을 deploy하는 script 추가
  package.json
  yarn.lock
Labels: enhancement

#36 [add] 디자인 시스템에 있는 아이콘 전부 반영 & Xlarge -> XLarge
  assets/images/icon/icon-adopt-xlarge-line.svg
  assets/images/icon/icon-analytics-large-line.svg
  assets/images/icon/icon-analytics-medium-line.svg
  assets/images/icon/icon-answer-xlarge-line.svg
  assets/images/icon/icon-arrow-medium-line.svg
  assets/images/icon/icon-arrow-small-line.svg
  assets/images/icon/icon-backward-large-line.svg
  assets/images/icon/icon-celebrate-xlarge-line.svg
  assets/images/icon/icon-check-large-fill.svg
  assets/images/icon/icon-check-large-line.svg
  assets/images/icon/icon-check-medium-fill.svg
  assets/images/icon/icon-check-medium-line.svg
  assets/images/icon/icon-check-small-fill.svg
  assets/images/icon/icon-checkCircle-medium-fill.svg
  assets/images/icon/icon-close-large-line.svg
  assets/images/icon/icon-close-xlarge-line.svg
  assets/images/icon/icon-comment-medium-line.svg
  assets/images/icon/icon-creditMinus-xlarge-line.svg
  assets/images/icon/icon-creditPlus-xlarge-line.svg
  assets/images/icon/icon-download-medium-line.svg
  assets/images/icon/icon-essay-large-line.svg
  assets/images/icon/icon-file-medium-line.svg
  assets/images/icon/icon-filter-large-line.svg
  assets/images/icon/icon-filter-medium-line.svg
  assets/images/icon/icon-hourglass-medium-line.svg
  assets/images/icon/icon-info-medium-fill.svg
  assets/images/icon/icon-info-medium-line.svg
  assets/images/icon/icon-interview-large-line.svg
  assets/images/icon/icon-jobWiki-medium-line.svg
  assets/images/icon/icon-keyline-large-line.svg
  assets/images/icon/icon-like-medium-fill.svg
  assets/images/icon/icon-like-xlarge-line.svg
  assets/images/icon/icon-megaphone-xlarge-line.svg
  assets/images/icon/icon-official-small-fill.svg
  assets/images/icon/icon-overflow-medium-fill.svg
  assets/images/icon/icon-plus-medium-line.svg
  assets/images/icon/icon-plus-small-line.svg
  assets/images/icon/icon-profile-large-fill.svg
  assets/images/icon/icon-question-medium-line.svg
  assets/images/icon/icon-question-xlarge-line.svg
  assets/images/icon/icon-reply-large-line.svg
  assets/images/icon/icon-resume-medium-line.svg
  assets/images/icon/icon-textArrow-large-line.svg
  assets/images/icon/icon-textArrow-medium-line.svg
  assets/images/icon/icon-textArrow-small-fill.svg
  assets/images/icon/icon-trash-medium-line.svg
  src/Components/Message/Tooltip.vue
  src/Elements/Core/Icon/Icon.vue
  stories/Icon/Icon.stories.js
  stories/Icon/Icon.stories.mdx
  stories/Icon/IconWrapper.vue
Labels: enhancement

#42 Update README.md
  README.md
Labels: documentation

#44 [change] Modal placeholder props & formValidator props
  src/Components/Message/Modal.vue
  stories/Modal/Modal.stories.js
Labels: enhancement

#45 [add] storybook viewport addon
  .storybook/main.js
  .storybook/preview.js
  package.json
  yarn.lock
Labels: enhancement

#46 [add] Card
  src/DataDisplay/Card.vue
  stories/Card/Card.stories.js
Labels: enhancement

#48 [add] husky && lint-staged
  package.json
  yarn.lock
Labels: enhancement

#51 [change] storybook deployer setting
  package.json
Labels: enhancement

#50 [fix] lint
  babel.config.js
  src/Components/Message/Toast.vue
Labels: bug

#53 [fix] Card component 등록
  src/Components/DataDisplay/Card.vue
  src/Components/DataDisplay/index.js
  stories/Card/Card.stories.js
Labels: bug

#59 [fix] Icon name props validator & color name props validator & docs
  src/Elements/Core/Icon/Icon.vue
  stories/Icon/Icon.stories.mdx
Labels: enhancement

#60 [change] xsmall size의 fontType은 caption2
  src/Components/Message/Callout.vue
Labels: enhancement

#62 [fix] Icon color
  src/DataEntry/SearchInput.vue
Labels: bug

#63 [fix] props default를 null로 변경 (빈값을 쓰지 않으면 validator에서 걸림)
  src/Elements/Core/Icon/Icon.vue
Labels: bug

#65 [fix] searchInput Icon css 정렬 오류
  src/DataEntry/SearchInput.vue
Labels: bug
