Repository comento/comento-ui, pull requests merged in 2021-06, with the labels that each got.

#490 [remove] swiper spacing 제한 해제
  src/Components/DataDisplay/Swiper.vue
Labels: enhancement

#489 [change] eduCard 모바일일 때, 썸네일 높이 120px로 변경
  src/Components/DataDisplay/EduCard.vue
Labels: enhancement

#493 [add] icons
  assets/images/icon/icon-clock-medium-line.svg
  assets/images/icon/icon-discount-medium-line.svg
  assets/images/icon/icon-star-large-fill.svg
  src/Elements/Core/Icon/Icon.vue
  stories/Icon/Icon.stories.mdx
Labels: documentation

#494 [change] ListItem padding-x 4px로 변경
  src/Components/DataDisplay/List/List/ListItem.vue
Labels: enhancement

#496 [remove] EduCard Mobile에서 hover scale 제거
  src/Components/DataDisplay/EduCard.vue
Labels: enhancement

#498 link icon 추가
  assets/images/icon/icon-link-medium-line.svg
  assets/images/icon/icon-link-small-line.svg
  src/Elements/Core/Icon/Icon.vue
  stories/Icon/Icon.stories.mdx
Labels: documentation, enhancement

#500 Feature/copy color files to dist
  package.json
  src/Components/DataDisplay/Swiper.vue
Labels: enhancement

#502 [add] radio button
  src/Components/DataEntry/RadioButton.vue
  src/Components/DataEntry/index.js
  stories/DataEntry/RadioButton.stories.mdx
Labels: documentation

#503 Icon 관련 컴포넌트 extends 방식으로 구조 변경, Select 디자인과 Icon 변경
  assets/images/icon/etc/icon-dropdown-medium-line-etc.svg
  assets/images/icon/etc/icon-dropdown-small-fill-etc.svg
  src/Components/DataEntry/Select.vue
  src/Elements/Core/Icon/AnimationIcon.vue
  src/Elements/Core/Icon/BaseIcon.vue
  src/Elements/Core/Icon/EtcIcon.vue
  src/Elements/Core/Icon/Icon.vue
  src/Elements/Core/Icon/index.js
  stories/DataEntry/Select.stories.mdx
  stories/Icon/AnimationIcon.stories.mdx
  stories/Icon/AnimationIconWrapper.vue
  stories/Icon/EtcIcon.stories.mdx
  stories/Icon/Icon.stories.mdx
  stories/Icon/IconWrapper.vue
Labels: documentation, enhancement
