Repository comento/comento-ui, pull requests merged in 2021-04, with the labels that each got.

#441 모바일 모달 width 100%로 변경
  src/Components/Message/Modal/BasicModal.vue
  src/Components/Message/Modal/WithFormModal.vue
Labels: bug

#442 포인터 커서 적용 (Select, Modal, FullscreenModal)
  src/Components/DataEntry/Select.vue
  src/Components/Message/Modal/FullscreenModal.vue
  src/Components/Message/Modal/Modal.vue
Labels: enhancement

#443 quill-editor 커스텀 스타일 코드 추가 (콘텐츠용 스타일, header 한글화)
  assets/style/quill/quill.init.scss
Labels: enhancement

#446 [add] EmptyBox 컴포넌트 추가
  assets/style/base/utils.scss
  src/Components/DataDisplay/EmptyBox.vue
  src/Components/DataDisplay/index.js
  stories/DataDisplay/EmptyBox.stories.mdx
Labels: enhancement

#447 [add] IconMegaphoneMediumLine
  assets/images/icon/icon-megaphone-medium-line.svg
  src/Elements/Core/Icon/Icon.vue
  stories/Icon/Icon.stories.mdx
Labels: documentation, enhancement

#449 [fix] callout 전체에 대한 click event가 close button에도 전달되는 것을 방지
  src/Components/Message/Callout.vue
Labels: bug

#453 [change] toast icon slot 추가
  src/Components/Message/Toast.vue
Labels: enhancement

#451 [add] 콜아웃 닫기버튼 커서 포인터 추가
  src/Components/Message/Callout.vue
Labels: enhancement

#455 [add] add chip type
  src/Components/DataDisplay/Chip.vue
  stories/DataDisplay/Chip.stories.mdx
Labels: enhancement

#457 [add] outline type 에만 투명 배경 prop 추가
  src/Components/DataDisplay/Chip.vue
  stories/DataDisplay/Chip.stories.mdx
Labels: enhancement

#458 Feature/fix tooltip style
  assets/style/tooltip/popover.scss
  assets/style/tooltip/tooltip.scss
  src/Components/Message/Tooltip.vue
Labels: bug

#461 [fix] eduCard caption divider
  src/Components/DataDisplay/EduCard.vue
Labels: bug

#462 [change] NewGrid max-width: 100vw로 변경
  src/Components/Layout/NewGrid.vue
Labels: bug

#460 Feature/change popover default property
  src/Components/Message/Popover.vue
  src/Components/Message/Tooltip.vue
  stories/Components/Message/Tooltip.stories.mdx
Labels: documentation, enhancement

#463 [add] EduCard chip slot, 스토리북 예시 추가
  src/Components/DataDisplay/EduCard.vue
  stories/Card/EduCard.stories.mdx
Labels: documentation, enhancement

#464 [change] outlined button background transparent로 변경
  src/Components/Button/Button.vue
Labels: bug
