Repository comento/comento-ui, pull requests merged in 2021-02, with the labels that each got.

#331 [add] Icons
  assets/images/icon/icon-download-medium-line.svg
  assets/images/icon/icon-file-small-line.svg
  assets/images/icon/icon-questionMark-small-fill.svg
  assets/images/icon/icon-setting-small-fill.svg
  src/Elements/Core/Icon/Icon.vue
  stories/Icon/Icon.stories.mdx
Labels: documentation, enhancement

#333 [change] green800 변경 (00992B -> 00B334)
  assets/style/base/color.scss
  src/Elements/Core/Colors/index.js
Labels: bug

#334 [change] Tab 내부를 slot으로 변경
  assets/style/base/mixins.scss
  src/Components/DataDisplay/Tabs.vue
  stories/DataDisplay/Tabs.stories.mdx
Labels: enhancement

#337 Feature/change tabs
  src/Components/DataDisplay/Tabs.vue
  stories/DataDisplay/Tabs.stories.mdx
Labels: documentation, enhancement

#336 [add] TellingAvatarQuote, mdx
  src/Components/Etc/TellingAvatarQuote.vue
  src/Components/Etc/index.js
  stories/Etc/TellingAvatarQuote.stories.mdx
Labels: enhancement

#340 Feature/change tabs with items
  src/Components/DataDisplay/Badge.vue
  src/Components/DataDisplay/Tabs.vue
  stories/DataDisplay/Badge.stories.mdx
  stories/DataDisplay/Tabs.stories.mdx
Labels: documentation, enhancement

#342 [add] full props 추가 (BasicModal, WithFormModal)
  src/Components/Message/Modal/BasicModal.vue
  src/Components/Message/Modal/WithFormModal.vue
  stories/Message/Modal/BasicModal.stories.mdx
  stories/Message/Modal/WithFormModal.stories.mdx
Labels: bug

#343 [add] TellingAvatarQuote 수정 (export, style)
  src/Components/Etc/TellingAvatarQuote.vue
  src/Components/index.js
Labels: bug, enhancement

#344 [change] Badge absolute class display inline-flex로 변경
  src/Components/DataDisplay/Badge.vue
Labels: bug

#348 Callout close 버튼 position, icon style mixin으로 변경
  src/Components/Message/Callout.vue
Labels: bug, enhancement

#347 [change] TellingAvatarQuote pc margin
  src/Components/Etc/TellingAvatarQuote.vue
Labels: enhancement

#349 Feature/change swiper
  src/Components/DataDisplay/Swiper.vue
  stories/DataDisplay/Swiper/Swiper.stories.mdx
Labels: documentation, enhancement

#352 [add] Callout icon slot, mdx 추가
  src/Components/Message/Callout.vue
  stories/Callout/Callout.stories.mdx
Labels: enhancement

#351 [add] icon-check-xlarge-fill
  assets/images/icon/icon-check-xlarge-fill.svg
  src/Elements/Core/Icon/Icon.vue
  stories/Icon/Icon.stories.mdx
Labels: enhancement

#350 Feature/change card
  src/Components/DataDisplay/Card.vue
  src/Components/DataDisplay/EduCard.vue
  src/Components/DataDisplay/index.js
  stories/Card/Card.stories.mdx
Labels: enhancement

#354 Callout css 추가
  src/Components/Message/Callout.vue
Labels: bug

#355 [add] typography elements dt 추가
  src/Elements/Core/Typography/Typography.vue
Labels: documentation

#356 TextField active color 오류 수정 및 로직개선(hint, focus 로직 개선) 및 persistentHint props 추가
  src/Components/DataEntry/TextField.vue
  stories/DataEntry/Textfield.stories.mdx
Labels: bug

#358 Select option이 label, value 구조일 경우 label 보여주기, mdx 추가
  src/Components/DataEntry/Select.vue
  stories/DataEntry/Select.stories.mdx
Labels: bug, documentation, enhancement

#359 [change] 아이콘 기본 cursor auto & 이벤트리스너가 있을 땐 pointer
  src/Elements/Core/Icon/Icon.vue
Labels: enhancement

#360 [fix] TellingAvatarQuote style 오류 수정
  src/Components/Etc/TellingAvatarQuote.vue
Labels: bug

#362 [fix] 초기 렌더링 시 object option을 가지고 있어도 select를 하기 전 value 그대로 노출되는 이슈 해결
  src/Components/DataEntry/Select.vue
  stories/DataEntry/Select.stories.mdx
Labels: bug

#364 [fix] created 로직을 watch로 이동
  src/Components/DataEntry/Select.vue
Labels: bug

#366 Select option icon 추가, icon-export-medium-line 이미지 추가
  assets/images/icon/icon-export-medium-line.svg
  assets/style/base/utils.scss
  src/Components/DataEntry/Select.vue
  src/Elements/Core/Icon/Icon.vue
  stories/DataEntry/Select.stories.mdx
  stories/Icon/Icon.stories.mdx
Labels: documentation, enhancement

#365 [add] Table 컴포넌트, mdx 추가
  src/Components/DataDisplay/Table.vue
  src/Components/DataDisplay/index.js
  stories/DataDisplay/Table.stories.mdx
Labels: documentation, enhancement
