Repository comento/comento-ui, pull requests merged in 2021-07, with the labels that each got.

#506 [add] Select size prop, update mdx docs
  src/Components/DataEntry/Select.vue
  stories/DataEntry/Select.stories.mdx
Labels: documentation, enhancement

#508 Feature/add icons
  assets/images/icon/icon-browse-medium-line.svg
  assets/images/icon/icon-video-medium-fill.svg
  assets/images/icon/icon-writing-2xlarge-line.svg
  src/Elements/Core/Icon/Icon.vue
  stories/Icon/Icon.stories.mdx
Labels: documentation, enhancement

#510 [add] avatar 커스텀 텍스트 추가
  src/Components/DataDisplay/Avatar.vue
  stories/DataDisplay/Avatar.stories.mdx
Labels: documentation, enhancement

#512 [remove] NarrowButton 색상 제한 제거
  src/Components/Button/NarrowButton.vue
  stories/Button/NarrowButton.stories.mdx
Labels: enhancement

#515 [add] Button 모바일에서는 active, focus 스타일 제거
  assets/style/base/mixins.scss
  src/Components/Button/Button.vue
Labels: enhancement

#514 [change] Tabs swiper 밑줄 기본으로 변경, 밑줄색 변경(gray200)
  src/Components/DataDisplay/Tabs.vue
Labels: bug

#517 [add] IconQuestionMediumLine
  assets/images/icon/icon-question-medium-line.svg
  stories/Icon/Icon.stories.mdx
Labels: bug

#516 [change] Content 리팩토링, docs 개선
  src/Components/DataDisplay/Content.vue
  stories/DataDisplay/Content.stories.mdx
Labels: documentation, enhancement

#519 [change] Content 컴포넌트, 폴더 구조 변경
  src/Components/DataDisplay/Content.vue
  src/Components/DataDisplay/Content/Content.vue
  src/Components/DataDisplay/Content/index.js
  src/Components/DataDisplay/index.js
  stories/DataDisplay/Content.stories.mdx
  stories/DataDisplay/Content/Content.stories.mdx
Labels: documentation, enhancement

#522 [add] Rating, RatingGroup 컴포넌트, 스토리북 추가
  src/Components/DataEntry/Rating/Rating.vue
  src/Components/DataEntry/Rating/RatingGroup.vue
  src/Components/DataEntry/Rating/index.js
  src/Components/DataEntry/index.js
  stories/DataEntry/Rating/Rating.stories.js
  stories/DataEntry/Rating/RatingGroup.stories.js
Labels: documentation, enhancement

#521 [add] ProfileWithText 컴포넌트, 스토리북 추가
  src/Components/DataDisplay/Content/ProfileWithText.vue
  src/Components/DataDisplay/Content/index.js
  stories/DataDisplay/Content.stories.mdx
  stories/DataDisplay/Content/ProfileWithText.stories.js
Labels: documentation, enhancement

#523 CoreCard 컴포넌트, 스토리북 추가
  src/Components/DataDisplay/Card/CoreCard.vue
  src/Components/DataDisplay/Card/EduCard.vue
  src/Components/DataDisplay/Card/index.js
  src/Components/DataDisplay/Content/Content.vue
  src/Components/DataDisplay/index.js
  stories/Card/CoreCard.stories.js
  stories/Card/EduCard.stories.mdx
  stories/DataDisplay/Content.stories.mdx
Labels: documentation, enhancement

#525 [fix] CoreCard 스토리북 이름 계층에 맞게 변경
  stories/Card/CoreCard.stories.js
Labels: bug

#527 [fix] Avatar height가 클 때 레이아웃 깨지는 오류 수정
  src/Components/DataDisplay/Avatar.vue
Labels: bug

#526 [change] Button secondary color 변경
  src/Components/Button/Button.vue
  src/Components/Other/Loader.vue
Labels: enhancement

#529 [add] IconTextArrowSmallLine
  assets/images/icon/icon-textArrow-small-line.svg
  src/Elements/Core/Icon/Icon.vue
  stories/Icon/Icon.stories.mdx
Labels: documentation, enhancement

#531 [remove] Content legacy stories
  stories/DataDisplay/Content.stories.mdx
Labels: bug
