Repository comento/comento-ui, pull requests merged in 2021-05, with the labels that each got.

#466 [add] 리스너 바인딩 추가
  src/Components/DataDisplay/EduCard.vue
Labels: enhancement

#469 [fix] event listeners binding
  src/Components/DataDisplay/Swiper.vue
  stories/DataDisplay/Swiper/Swiper.stories.mdx
Labels: bug

#471 [remove] 디자인 시스템 background color 제한 제거
  mixins/colorMixin.js
Labels: enhancement

#474 [add] Tooltip, Popover placement 추가 (right, right-top, right-bottom)
  assets/style/tooltip/common.scss
  src/Components/Message/Popover.vue
  src/Components/Message/Tooltip.vue
  stories/Components/Message/Popover.stories.mdx
  stories/Components/Message/Tooltip.stories.mdx
Labels: documentation, enhancement

#476 [add] gray250
  src/Elements/Core/Colors/Index.vue
  src/Elements/Core/Colors/index.js
Labels: documentation

#477 [add] IconMinusMediumLine
  assets/images/icon/icon-minus-medium-line.svg
  src/Elements/Core/Icon/Icon.vue
  stories/Icon/Icon.stories.mdx
Labels: documentation, enhancement

#479 SideDrawer width, height 변경
  src/Components/DataDisplay/Drawer/Drawer.vue
  src/Components/DataDisplay/Drawer/SideDrawer.vue
Labels: bug

#480 AlarmList, AlarmListItem 추가, List 폴더구조 변경
  src/Components/DataDisplay/FileItem.vue
  src/Components/DataDisplay/FileList.vue
  src/Components/DataDisplay/List/AlarmList/AlarmList.vue
  src/Components/DataDisplay/List/AlarmList/AlarmListItem.vue
  src/Components/DataDisplay/List/AlarmList/index.js
  src/Components/DataDisplay/List/List/List.vue
  src/Components/DataDisplay/List/List/ListItem.vue
  src/Components/DataDisplay/List/List/index.js
  src/Components/DataDisplay/List/index.js
  src/Components/DataDisplay/index.js
  src/Components/DataEntry/Select.vue
  stories/DataDisplay/List/AlarmList/AlarmList.stories.js
  stories/DataDisplay/List/AlarmList/AlarmListItem.stories.js
  stories/DataDisplay/List/List/List.stories.mdx
  stories/DataDisplay/List/List/ListItem.stories.mdx
  stories/DataDisplay/Table.stories.mdx
  stories/DataEntry/Dropdown.stories.mdx
Labels: documentation, enhancement

#483 [add] loop props 추가
  src/Components/DataDisplay/Swiper.vue
  stories/DataDisplay/Swiper/Swiper.stories.mdx
Labels: documentation, enhancement

#484 SideDrawer 변경 (align props 변경, 인터랙션 추가, 외부 스크롤 막기 추가)
  assets/style/base/animation.scss
  src/Components/DataDisplay/Drawer/Drawer.vue
  src/Components/DataDisplay/Drawer/SideDrawer.vue
  src/Components/DataDisplay/Drawer/SideDrawerExample.vue
Labels: documentation, enhancement

#486 AlarmListItem 기본 배경색 white
  src/Components/DataDisplay/List/AlarmList/AlarmListItem.vue
Labels: bug

#488 [change] headline5 line-height 수정
  src/Elements/Core/Typography/Typography.vue
Labels: enhancement

#487 [add] IconMegaphoneSmallLine
  assets/images/icon/icon-megaphone-small-line.svg
  src/Elements/Core/Icon/Icon.vue
  stories/Icon/Icon.stories.mdx
Labels: documentation, enhancement
