Repository comento/comento-ui, pull requests merged in 2021-09, with the labels that each got.

#573 [change] UserInformation 기본 padding 2px 0으로 변경
  src/Components/DataDisplay/Content/UserInformation.vue
Labels: enhancement

#572 [fix] Typography 띄어쓰기 없는 문장일 때 영역 초과하는 오류
  src/Elements/Core/Typography/Typography.vue
Labels: bug

#579 [fix] head slot이 있을 때만 head div 출력
  src/Components/DataDisplay/Table.vue
Labels: enhancement

#577 [fix] Select @input 추가
  src/Components/DataEntry/Select.vue
Labels: enhancement

#576 [fix] Reply showReport prop 추가
  src/Components/DataDisplay/Reply.vue
  stories/DataDisplay/Reply.stories.mdx
Labels: enhancement

#578 [fix] normal, full type에서 company없이 사용하는 경우 대응
  src/Components/DataDisplay/Content/UserInformation.vue
  stories/DataDisplay/Content/UserInformation.stories.mdx
Labels: documentation, enhancement

#582 [fix] userInformation style
  src/Components/DataDisplay/Content/UserInformation.vue
Labels: bug

#583 [fix] date picker append-to-body false
  src/Components/DataEntry/DatePicker.vue
Labels: enhancement

#585 [fix] Typography font-size, line-height math 함수 활용하는 mixin으로 변경
  src/Elements/Core/Typography/Typography.vue
Labels: 💄 style

#586 [fix] 아바타 id prop 추가 및 color와 연동
  src/Components/DataDisplay/Avatar.vue
  stories/DataDisplay/Avatar.stories.mdx
Labels: ✨ enhancement

#587 [fix] 버튼 클릭 이후에도 계속 포커스되는 현상 개선
  src/Components/Button/Button.vue
  src/Components/DataDisplay/Avatar.vue
  stories/DataDisplay/Avatar.stories.mdx
Labels: 🐛 bug

#590 [fix] Typography mixin 오류 수정
  src/Elements/Core/Typography/Typography.vue
Labels: 🐛 bug

#592 [change] 디자인시스템 컬러가 아니더라도 사용할 수 있게 수정
  src/Elements/Core/Typography/Typography.vue
Labels: ✨ enhancement

#596 [add] searchInput 아이콘 색상 변경 할 수 있도록 추가
  src/Components/DataEntry/SearchInput.vue
  stories/DataEntry/Dropdown.stories.mdx
Labels: 📖 documentation

#595 [change] Box element prop 추가
  src/Components/DataDisplay/Box.vue
  stories/Box/Box.stories.mdx
Labels: ✨ enhancement

#597 [change] color -> iconColor 명칭 통일
  src/Components/DataEntry/SearchInput.vue
  stories/DataEntry/Dropdown.stories.mdx
Labels: 📖 documentation
