Repository comento/comento-ui, pull requests merged in 2021-01, with the labels that each got.

#242 [fix] swiper.css에 있는 변수를 못 불러오는 이슈 해결
  plugins/index.js
  plugins/vue-awesome-swiper.js
  src/Components/DataDisplay/Swiper.vue
Labels: bug

#199 Feature/change tabs
  src/Components/DataDisplay/Tab.vue
  src/Components/DataDisplay/Tabs.vue
  src/Components/DataDisplay/index.js
  stories/DataDisplay/Tabs.stories.mdx
Labels: documentation, enhancement

#243 [change] swiper height 고정값 제거
  src/Components/DataDisplay/Swiper.vue
Labels: bug

#245 [fix] var 제거
  src/Components/DataDisplay/Swiper.vue
Labels: bug

#246 [add] isEmpty global method, badge 빈 값 체크
  mixins/globalMixin.js
  src/Components/DataDisplay/Badge.vue
Labels: bug

#249 [fix] props type File은 없음
  src/Components/DataDisplay/FileItem.vue
Labels: bug

#248 [fix] post css issue 해결
  assets/style/swiper/swiper.css
  plugins/vue-awesome-swiper.js
  src/Components/DataDisplay/Tabs.vue
Labels: bug

#251 [add] Badge getByte string으로 변환하는 코드 추가
  src/Components/DataDisplay/Badge.vue
Labels: enhancement

#252 Feature/fix swiper css issue
  plugins/index.js
  plugins/vue-awesome-swiper.js
  src/Components/DataDisplay/Swiper.vue
  src/Components/DataDisplay/Tabs.vue
  stories/DataDisplay/Swiper/Swiper.stories.mdx
  stories/DataDisplay/Swiper/SwiperItemExample.vue
Labels: bug

#255 Feature/fix swiper css issue
  assets/style/swiper/swiper.scss
  src/Components/DataDisplay/Swiper.vue
  src/Components/DataDisplay/Tabs.vue
Labels: bug

#254 Button disabled일 때 icon 색상, 커서 변경
  src/Components/Button/Button.vue
  stories/Button/Button.stories.mdx
Labels: bug

#256 [change] 색상값들을 변수명으로 치환
  src/Components/Button/Button.vue
Labels: enhancement

#257 [add] Typography element 추가 (strong, dd, em)
  src/Elements/Core/Typography/Typography.vue
Labels: enhancement

#259 [change] icon image fill 제거 (downloadLarge, profile xlarge, 2xlarge)
  assets/images/icon-edu-double-quote.svg
  assets/images/icon/icon-download-large-line.svg
  assets/images/icon/icon-keyline-large.svg
  assets/images/icon/icon-profile-2xlarge-fill.svg
  assets/images/icon/icon-profile-xlarge-fill.svg
  assets/images/icon/icon-security-large-fill.svg
  assets/images/icon/icon-sercurity-large-fill.svg
Labels: bug

#261 [fix] divider props 변경사항 적용
  src/Components/DataEntry/Select.vue
  stories/DataDisplay/List.stories.mdx
  stories/DataEntry/Dropdown.stories.mdx
Labels: bug

#262 [add] BasicModal content margin - not br 추가
  src/Components/Message/Modal/BasicModal.vue
Labels: bug

#263 스토리북 v1 변경사항 적용
  stories/DataDisplay/ChipGroup.stories.mdx
  stories/DataEntry/Dropdown.stories.mdx
  stories/DataEntry/Form.stories.mdx
  stories/DataEntry/InputGroup.stories.js
  stories/Message/Modal/WithFormModal.stories.mdx
Labels: bug

#266 [remove] addon-controls 제거
  .storybook/main.js
  package.json
  yarn.lock
Labels: enhancement

#267 [add] InputGroup mdx 추가 및 오류 수정
  stories/DataEntry/InputGroup.stories.js
  stories/DataEntry/InputGroup.stories.mdx
Labels: bug, enhancement

#268 Textarea props, Form 컴포넌트명, mdx 변경
  src/Components/DataEntry/FormGroup.vue
  src/Components/DataEntry/TextArea.vue
  src/Components/DataEntry/index.js
  stories/DataEntry/Form.stories.mdx
  stories/DataEntry/FormGroup.stories.mdx
Labels: enhancement

#270 [add] Tabs test용 배포
  src/Components/DataDisplay/Tabs.vue
Labels: enhancement

#272 quill style 추가
  assets/style/quill/quill.core.css
  assets/style/quill/quill.init.scss
  assets/style/quill/quill.scss
  assets/style/quill/quill.snow.css
  src/main.js
Labels: enhancement

#271 Feature/allow same file upload
  src/Components/DataEntry/FileInput.vue
  stories/DataEntry/FileInput.stories.mdx
Labels: documentation, enhancement

#274 [add] chip full 속성 추가
  src/Components/DataDisplay/Chip.vue
  src/Components/DataDisplay/ChipGroup.vue
  stories/DataDisplay/Chip.stories.mdx
  stories/DataDisplay/ChipGroup.stories.mdx
Labels: documentation

#273 Feature/add alert
  assets/style/base/variables.scss
  src/Components/Message/Alert.vue
  src/Components/Message/index.js
  stories/Alert/Alert.stories.mdx
Labels: documentation, enhancement

#279 [add] build chromatic on develop
  .github/workflows/chromatic-develop.yml
Labels: enhancement

#276 [add] List mdx example
  stories/DataDisplay/List.stories.mdx
Labels: documentation

#275 Feature/change tabs
  src/Components/DataDisplay/Tabs.vue
Labels: enhancement

#278 Feature/change popover
  assets/style/tooltip/common.scss
  assets/style/tooltip/popover.scss
  src/Components/Message/Popover.vue
  stories/Components/Message/Popover.stories.mdx
Labels: bug, documentation, enhancement

#281 [change] chromatic github action master에도 추가
  .github/workflows/chromatic-develop.yml
Labels: enhancement

#282 [change] active 안된 탭 아이템 글자색 변경
  src/Components/DataDisplay/Tabs.vue
Labels: enhancement

#285 [change] TextArea -> Textarea
  src/Components/DataEntry/Textarea.vue
  src/Components/DataEntry/index.js
  stories/DataEntry/FormGroup.stories.mdx
  stories/DataEntry/Textarea.stories.mdx
Labels: enhancement

#287 [add] Chip 이벤트리스너 추가
  src/Components/DataDisplay/Chip.vue
Labels: enhancement

#291 [add] dom7, swiper to transpileDependencies
  vue.config.js
Labels: bug

#293 [fix] 컴포넌트명과 name이 다른 이슈 해결
  src/Components/DataEntry/Select.vue
Labels: bug

#286 DatePicker, Hint 추가, input-border-color 변경(gray250)
  assets/style/base/color.scss
  assets/style/base/global.scss
  assets/style/datePicker/datePicker.init.scss
  assets/style/datePicker/datePicker.scss
  package.json
  src/Components/DataDisplay/Hint.vue
  src/Components/DataDisplay/index.js
  src/Components/DataEntry/DatePicker.vue
  src/Components/DataEntry/Input.vue
  src/Components/DataEntry/Select.vue
  src/Components/DataEntry/TextField.vue
  src/Components/DataEntry/Textarea.vue
  src/Components/DataEntry/index.js
  stories/DataEntry/DatePicker.stories.mdx
  yarn.lock
Labels: enhancement

#295 [fix] value가 안들어가는 이슈 해결
  src/Components/DataEntry/Textarea.vue
  stories/DataEntry/Textarea.stories.mdx
Labels: bug

#296 [add] FileItem isEdit 상태일 때 맨 좌측에 아이콘 추가
  src/Components/DataDisplay/FileItem.vue
Labels: enhancement

#297 [fix] FileItem loader size small
  src/Components/DataDisplay/FileItem.vue
Labels: bug

#301 [add] Textarea minHeight props 추가
  src/Components/DataEntry/Textarea.vue
  stories/DataEntry/Textarea.stories.mdx
Labels: enhancement

#300 DatePicker $listeners, props 추가 (editable, clearable)
  src/Components/DataEntry/DatePicker.vue
  stories/DataEntry/DatePicker.stories.mdx
Labels: enhancement

#302 [change] event 이름 변경
  src/Components/DataDisplay/FileItem.vue
  src/Components/DataDisplay/FileList.vue
  stories/DataEntry/FileInput.stories.mdx
Labels: enhancement

#304 Feature/add icon
  assets/images/icon/icon-video-large-fill.svg
  src/Elements/Core/Icon/Icon.vue
  stories/Icon/Icon.stories.mdx
Labels: documentation, enhancement

#303 [change] FileButton style
  src/Components/Button/FileButton.vue
Labels: enhancement

#306 [fix] 100% -> inherit, vertical이랑 horizontal 교체
  src/Elements/Utility/Divider.vue
Labels: bug

#310 Feature/apply divider change
  src/Components/DataEntry/Select.vue
  src/Elements/Utility/Divider.vue
  stories/DataDisplay/List.stories.mdx
  stories/DataEntry/Dropdown.stories.mdx
  stories/DataEntry/FileInput.stories.mdx
Labels: bug

#311 [remove] FileButton paddingX
  src/Components/Button/FileButton.vue
Labels: enhancement

#314 [add] DatePicker 캘린더 width 100%, height 조정
  src/Components/DataEntry/DatePicker.vue
Labels: enhancement

#315 [add] TextField full
  src/Components/DataEntry/TextField.vue
  stories/DataEntry/Textfield.stories.mdx
Labels: enhancement

#319 [change] Swiper indicator bottom style (10px -> 16px)
  assets/style/swiper/swiper.scss
Labels: enhancement

#320 Feature/fix textarea issue
  src/Components/DataEntry/Textarea.vue
  stories/DataEntry/Textarea.stories.mdx
Labels: bug

#318 DatePicker 개선 (editable 기본값 false, pointer, 코드 개선 등)
  assets/style/datePicker/datePicker.init.scss
  src/Components/DataEntry/DatePicker.vue
  stories/DataEntry/DatePicker.stories.mdx
Labels: enhancement

#322 [add] textarea listeners, attrs
  src/Components/DataEntry/Textarea.vue
Labels: enhancement

#324 [change] Checkbox border color (gray200 -> gray250)
  src/Components/DataEntry/Checkbox.vue
Labels: enhancement

#326 PermissionModal min-height, max-height 추가, Modal width 100% 전역 제거
  src/Components/Message/Modal/AlertModal.vue
  src/Components/Message/Modal/Modal.vue
  src/Components/Message/Modal/PermissionModal.vue
Labels: enhancement
