Repository comento/comento-ui, pull requests merged in 2021-03, with the labels that each got.

#369 [add] IconUncheckedXLargeFill
  assets/images/icon/icon-unchecked-xlarge-fill.svg
  src/Elements/Core/Icon/Icon.vue
  stories/Icon/Icon.stories.mdx
Labels: enhancement

#368 [add] Select option 글자색 추가 (gray800), label 로직 변경
  src/Components/DataEntry/Select.vue
Labels: bug

#371 [add] Chip, ChipGroup size props xlarge 속성 추가
  src/Components/DataDisplay/Chip.vue
  src/Components/DataDisplay/ChipGroup.vue
  stories/DataDisplay/Chip.stories.mdx
  stories/DataDisplay/ChipGroup.stories.mdx
Labels: documentation, enhancement

#372 [add] IconClockMediumFill
  assets/images/icon/icon-clock-medium-fill.svg
  src/Elements/Core/Icon/Icon.vue
  stories/Icon/Icon.stories.mdx
Labels: enhancement

#374 [add] release시 agit webhook 추가
  .github/workflows/propen.yml
Labels: enhancement

#376 [add] TextField autocomplete prop
  src/Components/DataEntry/TextField.vue
  stories/DataEntry/Textfield.stories.mdx
Labels: enhancement

#377 [add] spacing mixin
  assets/style/base/mixins.scss
  assets/style/base/utils.scss
Labels: enhancement

#378 [add] word break util style
  assets/style/base/utils.scss
Labels: enhancement

#379 [add] modal emit close event
  src/Components/Message/Modal/AlertModal.vue
  src/Components/Message/Modal/BasicModal.vue
  src/Components/Message/Modal/FullscreenModal.vue
  src/Components/Message/Modal/PermissionModal.vue
  src/Components/Message/Modal/WithFormModal.vue
Labels: enhancement

#382 [add] swiper slidesPerView auto 허용
  src/Components/DataDisplay/Swiper.vue
  stories/DataDisplay/Swiper/Swiper.stories.mdx
Labels: enhancement

#384 [fix] spacing을 가질 수 있는 조건 수정
  src/Components/DataDisplay/Swiper.vue
Labels: bug

#381 Checkbox size prop (xsmall, small, medium)
  src/Components/DataEntry/Checkbox.vue
  stories/DataEntry/Checkbox.stories.mdx
Labels: documentation, enhancement

#386 [change] .swiper 배경 색상 -> swiperItemExaple에 추가하였습니다
  src/Components/DataDisplay/Swiper.vue
  stories/DataDisplay/Swiper/SwiperItemExample.vue
Labels: documentation

#387 [add] EduCard style 추가
  src/Components/DataDisplay/EduCard.vue
  stories/Card/Card.stories.mdx
Labels: documentation

#388 Feature/change swiper
  src/Components/DataDisplay/Swiper.vue
  stories/DataDisplay/Swiper/Swiper.stories.mdx
  stories/DataDisplay/Swiper/SwiperItemExample.vue
Labels: documentation, enhancement

#390 [add] 아이콘 추가 (icon-support-medium-line.svg)
  assets/images/icon/icon-support-medium-line.svg
  src/Elements/Core/Icon/Icon.vue
  stories/Icon/Icon.stories.mdx
Labels: documentation, enhancement

#391 [add] 로고 색상 props 추가 (footer-회색, 종종 화이트 경우가 있음)
  assets/images/logo/logo-comento-horizontal.svg
  src/Elements/Core/Logo/Logo.vue
  stories/Logo/Logo.stories.mdx
Labels: documentation

#389 [add] TextField append slot, 스토리 추가
  src/Components/DataEntry/TextField.vue
  stories/DataEntry/Textfield.stories.mdx
Labels: documentation, enhancement

#396 Feature/fix tabs
  src/Components/DataDisplay/Tabs.vue
  stories/DataDisplay/Tabs.stories.mdx
Labels: bug

#397 Feature/change row and style col
  assets/style/base/mixins.scss
  assets/style/base/variables.scss
  src/Components/Layout/NewCol.vue
  src/Components/Layout/NewGrid.vue
  stories/Layout/NewLayout.stories.js
Labels: bug, documentation

#401 IconWrapper rotate 속성 추가, Icon mdx 코드 개선
  stories/Icon/Icon.stories.mdx
  stories/Icon/IconWrapper.vue
Labels: enhancement

#399 TextField id 속성 추가
  src/Components/DataEntry/TextField.vue
  stories/DataEntry/Textfield.stories.mdx
Labels: enhancement

#402 [add] star icon
  assets/images/icon/icon-star-4xlarge-fill.svg
  assets/images/icon/icon-star-medium-fill.svg
  assets/images/icon/icon-star-small-fill.svg
  assets/images/icon/icon-star-xlarge-fill.svg
  src/Elements/Core/Icon/Icon.vue
  stories/Icon/Icon.stories.mdx
Labels: documentation

#404 [fix] tabs
  src/Components/DataDisplay/Tabs.vue
Labels: bug

#405 [fix] Button primary-text-color 변경 (green800 -> green600)
  src/Components/Button/Button.vue
Labels: bug

#406 [change] colors
  assets/style/base/color.scss
  src/Elements/Core/Colors/index.js
Labels: enhancement

#409 [add] Hint align left
  src/Components/DataDisplay/Hint.vue
  src/Components/DataEntry/TextField.vue
Labels: bug

#408 Feature/register new layout components
  assets/style/base/mixins.scss
  assets/style/base/variables.scss
  src/Components/Layout/NewCol.vue
  src/Components/Layout/index.js
  stories/Layout/Layout.stories.js
  stories/Layout/NewLayout.stories.js
Labels: bug, enhancement

#410 Hint slot으로 변경, InputGroup Hint 예시 추가
  src/Components/DataDisplay/Hint.vue
  src/Components/DataEntry/DatePicker.vue
  src/Components/DataEntry/TextField.vue
  stories/DataEntry/InputGroup.stories.mdx
Labels: documentation, enhancement

#412 Feature/fix new col
  assets/style/base/mixins.scss
  stories/Layout/Layout.stories.js
Labels: bug

#414 [fix] newGrid style
  src/Components/Layout/NewGrid.vue
Labels: bug

#417 [change] NewGrid 클래스명 변경
  src/Components/Layout/NewCol.vue
  src/Components/Layout/NewGrid.vue
  src/Components/Layout/NewRow.vue
Labels: enhancement

#420 [fix] List margin
  src/Components/DataDisplay/List.vue
Labels: bug

#419 [change] Grid, NewGrid 스토리북 파일 분리
  stories/Layout/Grid.stories.js
  stories/Layout/NewGrid.stories.js
Labels: documentation

#421 Feature/change swiper
  src/Components/DataDisplay/Swiper.vue
  stories/DataDisplay/Swiper/Swiper.stories.mdx
Labels: bug, documentation, enhancement

#422 [fix] 초기 렌더링 시에는 input event emit 방지
  src/Components/DataEntry/Select.vue
Labels: bug

#424 [change] eduCard title props를 slot형태로 변경
  src/Components/DataDisplay/EduCard.vue
  stories/Card/Card.stories.mdx
Labels: enhancement

#426 Feature/fix select event
  src/Components/DataEntry/Select.vue
Labels: bug

#428 [fix] title slot default layout setting (typography)
  src/Components/DataDisplay/EduCard.vue
  stories/Card/Card.stories.mdx
Labels: enhancement

#433 [add] card hover interaction
  src/Components/DataDisplay/EduCard.vue
Labels: enhancement

#431 [change] headline1 line-height 변경
  src/Elements/Core/Typography/Typography.vue
Labels: enhancement

#430 [change] swiper autoplay delay 기본값 6초로 변경
  src/Components/DataDisplay/Swiper.vue
Labels: enhancement

#432 [change] footer icon 변경, educard 이미지 opacity 및 비율 변경
  assets/images/icon/icon-support-medium-line.svg
  src/Components/DataDisplay/EduCard.vue
Labels: enhancement

#435 [fix] hover 애니메이션 position 변경
  src/Components/DataDisplay/EduCard.vue
Labels: bug

#438 LinkButton to 속성이 없을 때 콘솔 오류 수정
  src/Components/Button/LinkButton.vue
  stories/Button/LinkButton.stories.mdx
Labels: bug

#439 [change] support medium line
  assets/images/icon/icon-support-medium-line.svg
Labels: documentation
