Repository comento/comento-ui, pull requests merged in 2022-02, with the labels that each got.

#701 Feature/change button
  src/components/components/general/button/Button.vue
  src/components/components/general/button/IconButton.vue
  src/components/components/other/Loader.vue
  stories/components/general/button/Button.stories.mdx
  stories/components/general/button/IconButton.stories.mdx
Labels: ✨ enhancement

#703 fix: loader story 오류 수정
  src/components/components/other/Loader.vue
  stories/components/other/Loader.stories.mdx
Labels: 🐛 bug

#702 feat: 로고 변경
  src/assets/images/logo/logo-comento-horizontal.svg
  src/assets/images/logo/logo-comento-typo-type.svg
  src/components/elements/core/logo/Logo.vue
  stories/elements/core/Logo.stories.mdx
Labels: ✨ enhancement

#705 feat: bottomNav에 필요한 아이콘 추가
  src/assets/images/icon/large/icon-edu-large-line.svg
  src/assets/images/icon/large/icon-pt-large-line.svg
  src/components/components/dataDisplay/Tabs.vue
  src/components/elements/core/icon/Icon.vue
  stories/elements/core/icon/Icon.stories.mdx
Labels: ✨ enhancement

#704 feat: NarrowButton 리뉴얼
  src/assets/style/base/color.scss
  src/components/components/general/button/NarrowButton.vue
  stories/components/general/button/NarrowButton.stories.mdx
Labels: ✨ enhancement

#706 Feature/badge
  src/components/components/dataDisplay/Badge.vue
  stories/components/dataDisplay/Badge.stories.mdx
Labels: ✨ enhancement

#710 Feature/change loader
  src/components/components/other/Loader.vue
  stories/components/other/Loader.stories.mdx
Labels: ✨ enhancement

#708 Feature/change icon
  src/assets/images/icon/2xlarge/icon-answer-2xlarge-line.svg
  src/assets/images/icon/2xlarge/icon-board-2xlarge-line.svg
  src/assets/images/icon/2xlarge/icon-changeJob-2xlarge-line.svg
  src/assets/images/icon/2xlarge/icon-checkRound-2xlarge-fill.svg
  src/assets/images/icon/2xlarge/icon-checkRound-2xlarge-line.svg
  src/assets/images/icon/2xlarge/icon-college-2xlarge-line.svg
  src/assets/images/icon/2xlarge/icon-job-2xlarge-line.svg
  src/assets/images/icon/2xlarge/icon-supervisor-2xlarge-line.svg
  src/assets/images/icon/4xlarge/icon-answer-4xlarge-line.svg
  src/assets/images/icon/4xlarge/icon-board-4xlarge-line.svg
  src/assets/images/icon/4xlarge/icon-changeJob-4xlarge-line.svg
  src/assets/images/icon/4xlarge/icon-college-4xlarge-line.svg
  src/assets/images/icon/4xlarge/icon-job-4xlarge-line.svg
  src/assets/images/icon/4xlarge/icon-star-4xlarge-fill.svg
  src/assets/images/icon/4xlarge/icon-supervisor-4xlarge-line.svg
  src/assets/images/icon/small/icon-check-small-fill.svg
  src/components/elements/core/icon/Icon.vue
  stories/elements/core/icon/Icon.stories.mdx
Labels: 🐛 bug

#711 feat: SearchInput 리뉴얼
  src/components/components/dataEntry/input/SearchInput.vue
  stories/components/dataEntry/input/SearchInput.stories.mdx
Labels: ✨ enhancement

#712 EduCard 리뉴얼
  src/components/components/dataDisplay/card/EduCard.vue
  stories/components/dataDisplay/card/EduCard.stories.mdx
Labels: ✨ enhancement

#713 Swiper 리뉴얼
  src/components/components/dataDisplay/Swiper.vue
  stories/components/dataDisplay/swiper/Swiper.stories.mdx
  stories/components/dataDisplay/swiper/SwiperItemExample.vue
Labels: ✨ enhancement

#715 button transparent hover 배경색 변경
  src/assets/style/base/color.scss
  stories/components/general/button/NarrowButton.stories.mdx
Labels: 📖 documentation, 💄 style

#719 Fix/redeem ver1
  src/components/components/dataDisplay/card/CoreCard.vue
  src/components/components/dataDisplay/card/EduCard.vue
Labels: 💄 style

#725 Feature/change icon
  src/assets/images/icon/2xlarge/icon-profile-2xlarge-fill.svg
  src/assets/images/icon/xlarge/icon-download-xlarge-line.svg
  src/components/elements/core/icon/Icon.vue
  stories/elements/core/icon/Icon.stories.mdx
Labels: ✨ enhancement

#721 Feature/change chip
  src/components/components/dataDisplay/chips/Chip.vue
  stories/components/dataDisplay/Chip.stories.mdx
Labels: ✨ enhancement
