Repository comento/comento-ui, pull requests merged in 2022-03, with the labels that each got.

#731 fix: swiper 요소가 모두 파싱 되고, init 되도록 변경
  src/components/components/dataDisplay/Swiper.vue
Labels: ✨ enhancement

#722 refactor: button에 state-style mixin 적용
  src/components/components/general/button/Button.vue
Labels: ✨ enhancement

#724 feat: Textarea 변경
  src/components/components/dataEntry/Textarea.vue
  stories/components/dataEntry/Textarea.stories.mdx
Labels: 🚫 do not merge

#729 feat: Toast 수정사항 변경
  src/components/components/message/Toast.vue
Labels: ✨ enhancement

#737 feat: PromotionEduCard 추가
  src/components/components/dataDisplay/card/PromotionEduCard.vue
  stories/components/dataDisplay/card/PromotionEduCard.stories.mdx
Labels: ✨ enhancement

#723 Feature/add ghost button
  src/components/components/general/button/Button.vue
  stories/components/general/button/Button.stories.mdx
Labels: ✨ enhancement

#728 feat: font semi-bold 추가
  src/assets/style/base/fonts.scss
Labels: 💄 style

#742 fix: 아이콘 이름 변경
  stories/components/dataDisplay/Reply.stories.mdx
  stories/components/dataDisplay/card/CoreCard.stories.mdx
  stories/components/dataDisplay/content/ProfileWithText.stories.js
  stories/components/dataDisplay/content/UserInformation.stories.mdx
  stories/components/etc/TellingAvatarQuote.stories.mdx
Labels: 🐛 bug

#743 feat: ghostButton disabled일 때 background 제거
  src/components/components/general/button/Button.vue
  stories/components/general/button/Button.stories.mdx
Labels: ✨ enhancement

#738 Feature/change avatar
  src/components/components/dataDisplay/Avatar.vue
  stories/components/dataDisplay/Avatar.stories.mdx
Labels: ✨ enhancement

#739 feat: EmptyBox 교체
  src/components/components/dataDisplay/EmptyBox.vue
  stories/components/dataDisplay/EmptyBox.stories.mdx
Labels: ✨ enhancement

#744 Feature/change textfield
  src/components/components/dataDisplay/Hint.vue
  src/components/components/dataEntry/input/TextField.vue
  stories/components/dataEntry/input/Textfield.stories.mdx
Labels: ✨ enhancement

#749 feat: fab button에 옮김
  src/components/components/general/button/Button.vue
  src/components/components/general/button/FAB.vue
  stories/components/general/button/FAB.stories.mdx
Labels: ✨ enhancement

#747 Feature/change rating
  src/components/components/dataDisplay/rating/IconRating.vue
  src/components/components/dataDisplay/rating/TextRating.vue
  src/components/components/dataDisplay/rating/TextRatingWrapper.vue
  src/components/components/dataDisplay/rating/index.js
  stories/components/dataDisplay/rating/IconRating.stories.mdx
  stories/components/dataDisplay/rating/TextRating.stories.mdx
Labels: ✨ enhancement

#748 feat: FAB component, story 추가
  src/components/components/general/button/Button.vue
Labels: ✨ enhancement

#750 feat: avatar text -> nickname type
  stories/components/dataDisplay/Reply.stories.mdx
  stories/components/dataDisplay/card/CoreCard.stories.mdx
  stories/components/dataDisplay/content/ProfileWithText.stories.js
  stories/components/dataDisplay/content/UserInformation.stories.mdx
Labels: ✨ enhancement

#751 feat: button secondary -> info
  src/components/components/general/button/Button.vue
  stories/components/general/button/Button.stories.mdx
  stories/components/general/button/ButtonGroup.stories.mdx
Labels: ✨ enhancement

#755 Feature/pagination
  package.json
  src/components/components/dataDisplay/CustomPagination.vue
  src/components/components/dataDisplay/Pagination.vue
  src/components/components/dataDisplay/index.js
  stories/components/dataDisplay/Pagination.stories.mdx
Labels: ✨ enhancement, 🚫 do not merge

#759 feat: font-weight 변경
  src/assets/style/base/fonts.scss
  src/assets/style/base/mixins.scss
  src/assets/style/base/utils.scss
  src/assets/style/base/variables.scss
  src/assets/style/quill/quill.snow.css
  src/components/components/dataDisplay/CustomPagination.vue
  src/components/components/dataDisplay/chips/Chip.vue
  src/components/components/dataEntry/input/SearchInput.vue
  src/components/components/general/button/Button.vue
  src/components/components/message/Alert.vue
  src/components/components/message/Callout.vue
  src/components/elements/core/typography/Typography.vue
Labels: ✨ enhancement

#757 fix: TextRating component 등록
  src/components/components/dataDisplay/card/CoreCard.vue
  src/components/components/dataDisplay/rating/IconRating.vue
  src/components/components/dataDisplay/rating/Rating.vue
  src/components/components/dataDisplay/rating/RatingGroup.vue
  src/components/components/dataDisplay/rating/index.js
  stories/components/dataDisplay/card/CoreCard.stories.mdx
  stories/components/dataDisplay/rating/Rating.stories.js
  stories/components/dataDisplay/rating/RatingGroup.stories.js
Labels: 🐛 bug

#760 feat: withCloseButton props 추가
  src/components/components/dataDisplay/chips/Chip.vue
  stories/components/dataDisplay/Chip.stories.mdx
Labels: ✨ enhancement

#768 fix: caption2 line-height 오류 수정
  src/assets/style/base/mixins.scss
Labels: 💄 style

#769 feat: Typography font-weight props 변경
  src/assets/style/base/mixins.scss
  src/assets/style/base/utils.scss
  src/components/components/dataDisplay/EmptyBox.vue
  src/components/components/dataDisplay/content/ProfileWithText.vue
  src/components/components/dataDisplay/content/UserInformation.vue
  src/components/components/etc/TellingAvatarQuote.vue
  src/components/components/message/modal/PermissionModal.vue
  src/components/elements/core/typography/Typography.vue
  stories/components/dataDisplay/card/CoreCard.stories.mdx
Labels: ✨ enhancement

#774 feat: info color 변경
  src/components/components/other/Loader.vue
Labels: ✨ enhancement

#776 fix: Banner QA 반영
  src/components/components/message/Banner.vue
  stories/components/message/Banner.stories.mdx
Labels: ✨ enhancement

#771 feat: logo type background image 변경
  src/components/components/dataDisplay/Avatar.vue
Labels: ✨ enhancement

#781 feat: Typography font-weight 변경
  src/assets/style/base/utils.scss
  src/components/components/dataDisplay/Avatar.vue
  src/components/components/dataDisplay/Badge.vue
  src/components/components/dataDisplay/drawer/BottomDrawer.vue
  src/components/components/dataDisplay/drawer/SideDrawer.vue
  src/components/elements/core/typography/Typography.vue
Labels: ✨ enhancement

#787 fix: 스토리에서 컬러 잘못들어간 오류 수정
  stories/components/dataDisplay/Tabs.stories.mdx
  stories/components/dataDisplay/rating/RatingGroup.stories.js
Labels: 🐛 bug

#784 feat: IconRating컴포넌트 text prop Number type 추가
  src/components/components/dataDisplay/rating/IconRating.vue
Labels: ✨ enhancement

#786 feat: DatePicker new 컬러 반영
  src/components/components/dataEntry/DatePicker.vue
Labels: ✨ enhancement

#785 feat: RadioButton new 컬러 반영
  src/components/components/dataEntry/RadioButton.vue
  stories/components/dataEntry/RadioButton.stories.mdx
Labels: ✨ enhancement

#788 feat: Hint컴포넌트에서 color prop 기본값 변경
  src/components/components/dataDisplay/Hint.vue
Labels: ✨ enhancement

#790 feat: eduCard, PromotionEduCard slot name 컨벤션에 맞게 변경
  src/components/components/dataDisplay/card/EduCard.vue
  src/components/components/dataDisplay/card/PromotionEduCard.vue
  stories/components/dataDisplay/card/EduCard.stories.mdx
  stories/components/dataDisplay/card/PromotionEduCard.stories.mdx
Labels: ✨ enhancement

#779 feat: IconAnswerXLargeLine 추가
  src/assets/images/icon/xlarge/icon-answer-xlarge-line.svg
  src/components/elements/core/icon/Icon.vue
  stories/elements/core/icon/Icon.stories.mdx
Labels: ✨ enhancement

#800 feat: border-radius 변경
  src/components/components/dataDisplay/Tabs.vue
  src/components/components/dataDisplay/card/CoreCard.vue
  src/components/components/dataEntry/Checkbox.vue
  src/components/components/general/button/Button.vue
  src/components/components/message/Callout.vue
Labels: 💄 style

#799 feat: 스토리에서 chip 변경
  stories/components/dataDisplay/card/CoreCard.stories.mdx
Labels: 💄 style

#792 feat: icon 추가 (information-small line, fill)
  src/assets/images/icon/small/icon-information-small-fill.svg
  src/assets/images/icon/small/icon-information-small-line.svg
  src/components/elements/core/icon/Icon.vue
  stories/elements/core/icon/Icon.stories.mdx
Labels: ✨ enhancement

#805 fix: font-weight가 없을 때 f-null로 클래스 주입되는 오류 수정
  src/components/elements/core/typography/Typography.vue
Labels: 🐛 bug

#806 feat: pagination컴포넌트에 displayName 주석 추가
  src/components/components/dataDisplay/Pagination.vue
Labels: 📖 documentation

#807 feat: searchInput paddingY값 변경
  src/components/components/dataEntry/input/SearchInput.vue
Labels: 💄 style

#808 Feature/feedback button
  src/components/components/general/button/Button.vue
  src/components/components/general/button/LinkButton.vue
  src/components/components/other/Loader.vue
  stories/components/general/button/Button.stories.mdx
  stories/components/general/button/LinkButton.stories.mdx
  yarn.lock
Labels: 💄 style, 🚫 do not merge

#775 feat: 글자색 기본값 넣기
  stories/components/dataDisplay/rating/TextRating.stories.mdx
Labels: ✨ enhancement, 🚫 do not merge

#777 feat: EduCard QA
  src/components/components/dataDisplay/card/EduCard.vue
  stories/components/dataDisplay/card/EduCard.stories.mdx
Labels: ✨ enhancement

#783 Feature/chip qa
  src/components/components/dataDisplay/chips/Chip.vue
Labels: ✨ enhancement, 🚫 do not merge

#791 Feature/list qa
  src/components/components/dataDisplay/list/fileList/FileItem.vue
  src/components/components/dataDisplay/list/fileList/FileSummary.vue
  src/components/components/dataDisplay/list/list/List.vue
  src/components/components/dataDisplay/list/list/ListItem.vue
  stories/components/dataDisplay/list/fileList/FileList.stories.mdx
Labels: ✨ enhancement, 🚫 do not merge

#796 fix: narrowButton QA 오류 반영
  src/components/components/general/button/NarrowButton.vue
  stories/components/general/button/NarrowButton.stories.mdx
Labels: 💄 style, 🚫 do not merge

#797 feat: checkbox 체크 아이콘 변경
  src/components/components/dataEntry/Checkbox.vue
Labels: 💄 style, 🚫 do not merge

#801 fix: circle 그림자 추가 & 스와이퍼 속도 낮춤 반영
  src/components/components/dataDisplay/Swiper.vue
Labels: 💄 style, 🚫 do not merge

#802 Feature/callout qa
  src/components/components/message/Callout.vue
  stories/components/message/Callout.stories.mdx
Labels: 🐛 bug, 🚫 do not merge

#804 feat: ratingButton 추가
  src/components/components/general/button/RatingButton.vue
  stories/components/general/button/RatingButton.stories.mdx
Labels: 📖 documentation, ✨ enhancement, 🚫 do not merge

#817 feat: 텍스트 없을 때 버튼에 disabled 추가
  src/components/components/dataEntry/Textarea.vue
Labels: ✨ enhancement

#815 fix: title font-weight 수정
  src/components/components/dataDisplay/card/EduCard.vue
Labels: ✨ enhancement

#816 fix: 스와이퍼 5000 -> 3000변경
  src/components/components/dataDisplay/Swiper.vue
Labels: ✨ enhancement

#820 fix: button qa
  src/components/components/general/button/Button.vue
  stories/components/general/button/Button.stories.mdx
Labels: ✨ enhancement

#822 Feature/file input qa
  stories/components/dataEntry/FileInput.stories.mdx
Labels: 🐛 bug

#821 fix: font-weight 수정
  src/components/components/general/button/Button.vue
Labels: ✨ enhancement

#819 Feature/callout qa
  src/components/components/dataDisplay/chips/Chip.vue
  src/components/components/message/Callout.vue
Labels: 🐛 bug

#810 fix: 모바일에서 이름 나오는 오류 수정
  src/components/components/etc/TellingAvatarQuote.vue
Labels: 🐛 bug, 💄 style

#811 feat: iconButton type props 추가
  src/components/components/general/button/IconButton.vue
  stories/components/general/button/IconButton.stories.mdx
Labels: ✨ enhancement

#814 feat: underline, outline 클래스가 프로덕트단에서 겹치므로 클래스명 변경
  src/components/components/dataEntry/Select.vue
  src/components/components/dataEntry/input/TextField.vue
Labels: 🐛 bug

#824 feat: closeIcon color gray500으로 변경
  src/components/components/message/modal/FullscreenModal.vue
  src/components/components/message/modal/Modal.vue
Labels: ✨ enhancement

#823 fix: @click="$event.target.blur()"은 click 이후에 focus가 유지되는 현상 방지
  src/components/components/dataEntry/Checkbox.vue
Labels: 🐛 bug

#812 feat: iconButton컴포넌트에 rotate prop 추가
  src/components/components/general/button/IconButton.vue
  stories/components/general/button/IconButton.stories.mdx
Labels: ✨ enhancement

#818 Feature/chip qa
  src/components/components/dataDisplay/chips/Chip.vue
  stories/components/dataDisplay/Chip.stories.mdx
Labels: 🐛 bug

#813 Feature/file list qa
  src/components/components/dataDisplay/list/fileList/FileItem.vue
  src/components/components/dataDisplay/list/list/ListItem.vue
  stories/components/dataDisplay/list/fileList/FileList.stories.mdx
Labels: ✨ enhancement

#825 fix: 색상변경 반영
  src/assets/style/animation/icon-checkRound-line-animation.scss
Labels: ✨ enhancement

#828 feat: ratingButton 컴포넌트 등록코드 추가
  src/components/components/general/button/index.js
Labels: 🐛 bug

#832 fix: EduCard max-width 삭제
  src/components/components/dataDisplay/card/EduCard.vue
Labels: 🐛 bug

#831 feat: Chip, NarrowButton에 state-style 적용
  src/components/components/dataDisplay/chips/Chip.vue
  src/components/components/general/button/NarrowButton.vue
Labels: ✨ enhancement

#835 feat: LinkButton 스타일 state-style로 변경
  src/components/components/general/button/LinkButton.vue
Labels: 💄 style

#833 feat: Dropdown 리스트 스타일 변경
  src/components/components/dataEntry/Dropdown.vue
  stories/components/dataEntry/Dropdown.stories.mdx
Labels: 💄 style

#834 feat: Chip color 추가 (secondary, error)
  src/components/components/dataDisplay/chips/Chip.vue
Labels: ✨ enhancement

#838 feat: Chip small에 line-height 16px 추가
  src/components/components/dataDisplay/chips/Chip.vue
Labels: 🐛 bug

#841 fix: full, closable일 때 아이콘이 오른쪽 끝으로 안가는 이슈 해결
  src/components/components/message/Callout.vue
  stories/components/message/Callout.stories.mdx
Labels: 🐛 bug

#845 fix: state-style 로직 수정
  src/assets/style/base/mixins.scss
Labels: 🐛 bug

#846 fix: Tabs 모바일 버튼 스타일 오류 수정
  src/components/components/dataDisplay/Tabs.vue
Labels: 🐛 bug

#850 fix: Tabs에서 swiper일 때도 withHeader 추가
  src/components/components/dataDisplay/Tabs.vue
Labels: 🐛 bug

#849 fix: 에디터 하이퍼링크 색상 변경
  src/assets/style/quill/quill.init.scss
Labels: 🐛 bug, 💄 style

#848 fix: TextField outline일 때 append border-radius 추가
  src/components/components/dataEntry/input/TextField.vue
Labels: 🐛 bug, 💄 style

#851 fix: 에디터에서 글자크기 label 스타일 오류 수정
  src/assets/style/quill/quill.init.scss
Labels: 💄 style

#852 feat: IconThreeDotLargeFill 추가
  src/assets/images/icon/large/icon-threeDot-large-fill.svg
  src/components/elements/core/icon/Icon.vue
  stories/elements/core/icon/Icon.stories.mdx
Labels: ✨ enhancement

#854 feat: body1 letter-spacing 변경
  src/assets/style/base/mixins.scss
Labels: ✨ enhancement

#856 fix: state-style 모바일, PC 모두 변경
  src/assets/style/base/mixins.scss
Labels: 🐛 bug

#857 feat: Alert 컴포넌트 변경
  src/assets/images/icon/medium/icon-checkRound-medium-line.svg
  src/assets/images/icon/medium/icon-selected-medium-line.svg
  src/assets/style/base/variables.scss
  src/components/components/message/Alert.vue
  src/components/elements/core/icon/Icon.vue
  stories/components/message/Alert.stories.mdx
  stories/elements/core/icon/Icon.stories.mdx
Labels: 📖 documentation, ✨ enhancement
