Repository comento/comento-ui, pull requests merged in 2022-06, with the labels that each got.

#909 fix: Select small 사이즈 제대로 적용 안된 문제 수정
  src/components/components/dataEntry/Select.vue
Labels: 🐛 bug

#891 chore: Visual Studio Code 자동완성 대응 추가
  .github/workflows/build-test.yml
  .github/workflows/chromatic-develop.yml
  .github/workflows/chromatic.yml
  .github/workflows/shipjs-trigger.yml
  .github/workflows/storybook-deployer.yml
  CHANGELOG.md
  package.json
  yarn.lock
Labels: ✨ enhancement

#912 fix: NarrowButton icon 수평 맞추기
  src/components/components/general/button/NarrowButton.vue
Labels: 🐛 bug, 💄 style

#914 feat: 아이콘 3개 추가
  src/assets/images/icon/2xlarge/icon-plus-2xlarge-line.svg
  src/assets/images/icon/2xlarge/icon-support-2xlarge-line.svg
  src/assets/images/icon/4xlarge/icon-star-4xlarge-line.svg
  src/components/elements/core/icon/Icon.vue
  stories/elements/core/icon/Icon.stories.mdx
Labels: ✨ enhancement

#915 Feature/webview optimization
  src/assets/style/base/fonts.scss
Labels: ✨ enhancement

#916 fix: Textarea placeholder 폰트 크기 수정
  src/components/components/dataEntry/Textarea.vue
Labels: 🐛 bug

#918 feat: 아이콘 2개 추가
  src/assets/images/icon/medium/icon-analytics-medium-line.svg
  src/assets/images/icon/medium/icon-resume-medium-line.svg
  src/components/elements/core/icon/Icon.vue
  stories/elements/core/icon/Icon.stories.mdx
Labels: ✨ enhancement

#920 feat: IconMuteXLargeLine, IconVolumeXLargeLine 추가
  src/assets/images/icon/xlarge/icon-mute-xlarge-line.svg
  src/assets/images/icon/xlarge/icon-volume-xlarge-line.svg
  src/components/elements/core/icon/Icon.vue
  stories/elements/core/icon/Icon.stories.mdx
Labels: ✨ enhancement
