Repository comento/comento-ui, pull requests merged in 2022-12, with the labels that each got.

#955 xsmall export icon 추가
  src/assets/images/icon/xsmall/icon-export-xsmall-line.svg
  src/components/elements/core/icon/Icon.vue
  stories/elements/core/icon/Icon.stories.mdx
Labels: ✨ enhancement

#959 fix: 닫기 버튼 아이콘 색상 변경
  src/components/components/dataDisplay/drawer/Drawer.vue
  src/components/components/message/modal/Modal.vue
Labels: 💄 style

#961 fix: 오류 수정(아이콘 크기, 스토리북)
  src/components/components/dataDisplay/Avatar.vue
  src/components/components/dataDisplay/card/PromotionEduCard.vue
  src/components/components/dataDisplay/chips/Chip.vue
  src/components/components/dataEntry/RadioButton.vue
  src/components/components/message/Alert.vue
  src/components/components/message/Banner.vue
  src/components/components/message/Callout.vue
  stories/components/dataEntry/input/Textfield.stories.mdx
  stories/components/general/button/IconButton.stories.mdx
  stories/components/message/Alert.stories.mdx
  stories/components/message/Banner.stories.mdx
Labels: 🐛 bug

#964 feat: font에 cdn 주소 추가
  src/assets/style/base/fonts.scss
Labels: 🐛 bug

#968 feat: Tooltip left 방향 추가
  src/assets/style/tooltip/common.scss
  src/components/components/message/Tooltip.vue
  src/utils/constants/tooltip.js
  stories/components/message/Tooltip.stories.mdx
Labels: ✨ enhancement
