Repository comento/comento-ui, pull requests merged in 2022-05, with the labels that each got.

#886 fix: medium ListItem 상하 패딩 수정
  src/components/components/dataDisplay/list/list/ListItem.vue
Labels: 🐛 bug

#887 fix: Chip transparent 우선순위 변경
  src/components/components/dataDisplay/chips/Chip.vue
Labels: 🐛 bug

#888 feat: AlarmList에서 Divider 제거
  src/components/components/dataDisplay/list/alarmList/AlarmList.vue
  stories/components/dataDisplay/list/alarmList/AlarmList.stories.js
Labels: ✨ enhancement

#890 feat: FullscreenModal 변경
  src/components/components/message/modal/FullscreenModal.vue
  stories/components/message/modal/FullscreenModal.stories.mdx
Labels: ✨ enhancement

#893 fix: 스토리 오류 수정
  stories/components/message/modal/FullscreenModal.stories.mdx
Labels: 🐛 bug, 📖 documentation

#896 fix: FullscreenModal 인터랙션, 스토리 개선
  src/components/components/message/modal/FullscreenModal.vue
  stories/components/message/modal/FullscreenModal.stories.mdx
Labels: 🐛 bug, 📖 documentation, ✨ enhancement

#895 fix: FullscreenModal 버튼 디자인 수정
  src/components/components/message/modal/FullscreenModal.vue
Labels: 💄 style

#901 feat: Loader xlarge size 추가
  src/assets/images/icon/xlarge/icon-spinner-xlarge.svg
  src/components/components/other/Loader.vue
  stories/components/other/Loader.stories.mdx
Labels: ✨ enhancement

#900 feat: FileList spacing 제거
  src/components/components/dataDisplay/list/fileList/FileList.vue
Labels: 💄 style

#899 fix: FullscreenModal actionButton 여백 수정
  src/components/components/message/modal/FullscreenModal.vue
Labels: 🐛 bug, 💄 style

#902 feat: IconVodProductLargeLine 추가
  src/assets/images/icon/large/icon-vod-product-large-line.svg
  src/components/elements/core/icon/Icon.vue
  stories/elements/core/icon/Icon.stories.mdx
Labels: ✨ enhancement

#904 feat: IconVodMediumLine 추가
  src/assets/images/icon/medium/icon-vod-medium-line.svg
  src/components/elements/core/icon/Icon.vue
  stories/elements/core/icon/Icon.stories.mdx
Labels: ✨ enhancement
