Repository comento/comento-ui, pull requests merged in 2023-02, with the labels that each got.

#992 fix: Label 스타일 변경
  src/components/components/dataDisplay/Label.vue
Labels: 💄 style

#998 fix: 아이콘이 나오지 않는 오류 수정
  src/components/components/dataEntry/input/SearchInput.vue
Labels: 🐛 bug

#1005 feat: 아이콘 5개 추가
  src/assets/images/icon/large/icon-businessCase-large-line.svg
  src/assets/images/icon/large/icon-class-large-line.svg
  src/assets/images/icon/small/icon-bad-small-line.svg
  src/assets/images/icon/small/icon-good-small-line.svg
  src/assets/images/icon/small/icon-search-small-line.svg
  src/components/elements/core/icon/Icon.vue
  stories/elements/core/icon/Icon.stories.mdx
Labels: ✨ enhancement

#1007 Feature/add icon
  src/assets/images/icon/large/icon-businessCase-large-line.svg
  src/assets/images/icon/large/icon-class-large-line.svg
  src/assets/images/icon/small/icon-bad-small-line.svg
  src/assets/images/icon/small/icon-good-small-line.svg
  src/assets/images/icon/small/icon-search-small-line.svg
Labels: 🐛 bug

#1013 feat: 하이라이트 스타일 변경
  src/assets/style/base/utils.scss
Labels: 💄 style
