Repository comento/comento-ui, pull requests merged in 2023-03, with the labels that each got.

#1022 feat: hide-scrollbar 유틸 함수 추가
  src/assets/style/base/mixins.scss
  src/assets/style/base/utils.scss
Labels: 💄 style

#1047 Develop <- Develop alpha
  CHANGELOG.md
  package.json
  src/assets/images/icon/large/icon-businessCase-large-line.svg
  src/assets/images/icon/large/icon-class-large-line.svg
  src/assets/style/base/mixins.scss
  src/assets/style/base/utils.scss
  src/components/components/dataDisplay/EmptyBox.vue
  src/components/components/dataDisplay/Label.vue
  src/components/components/dataDisplay/Tabs.vue
  src/components/components/dataDisplay/list/list/ListItem.vue
  src/components/components/dataEntry/Dropdown.vue
  src/components/components/dataEntry/Select.vue
  src/components/components/dataEntry/input/SearchInput.vue
  src/components/components/general/button/LinkButton.vue
  src/components/components/index.js
  src/components/components/message/Popover.vue
  src/components/components/message/modal/FullscreenModal.vue
  src/components/components/navigation/Header.vue
  src/components/components/navigation/SearchTopBar.vue
  src/components/components/navigation/SubHeader.vue
  src/components/components/navigation/TopBar.vue
  src/components/components/navigation/index.js
  src/components/elements/core/icon/Icon.vue
  src/mixins/windowMixin.js
  stories/components/dataEntry/Dropdown.stories.mdx
  stories/components/general/button/LinkButton.stories.mdx
  stories/components/navigation/Header.stories.mdx
  stories/components/navigation/SearchTopBar.stories.mdx
  stories/components/navigation/SubHeader.stories.mdx
  stories/components/navigation/TopBar.stories.mdx
Labels: ✨ enhancement, 🚫 do not merge

#1052 fix: 헤더 로고 오류 수정
  src/components/components/navigation/Header.vue
  src/components/components/navigation/TopBar.vue
Labels: 🐛 bug
