Repository comento/comento-ui, pull requests merged in 2024-05, with the labels that each got.

#1131 fix: 헤더 스타일 오류 수정
  src/components/components/dataEntry/input/SearchInput.vue
  src/components/components/navigation/Header.vue
Labels: 🐛 bug

#1130 search input pc 규격 변경
  src/components/components/dataEntry/input/SearchInput.vue
Labels: ✨ enhancement

#1134 refactor: Badge 코드 변경
  src/components/components/dataDisplay/Badge.vue
Labels: 💄 style

#1136 fix: Badge 한 글자 측정하는 조건 오류 수정
  src/components/components/dataDisplay/Badge.vue
Labels: 🐛 bug

#1138 fix: Badge text가 왼쪽으로 쏠려보이는 오류 수정
  src/components/components/dataDisplay/Badge.vue
Labels: 🐛 bug
